### PR TITLE
[READY] Issue #1876 - Updated refreshChoicesCallback() to take into account current query string

### LINKED ISSUE #1876: hs.chooser:refreshChoicesCallback() doesn't take into account query string?
When you trigger `hs.chooser:refreshChoicesCallback()` it doesn't seem to take into account the current query string?

For example, if you have the following choices:

```
a1
a2
a3
b1
b2
b3
```

...and your query string is "a", you'll only see the choices starting with "a".

However, if you trigger `:refreshChoicesCallback()` via a contextual menu, it reloads all the choices, but doesn't take into account the existing query string value, so "b1", "b2" and "b3" are now visible, even though the query string still says "a".

Here's some test code:

```lua
test = hs.chooser.new(function(result)
	print(string.format("Result: %s", hs.inspect(result)))
end)

local function getChoices()
	return {
		{ ["text"] = "a1" },
		{ ["text"] = "a2" }, 
		{ ["text"] = "a3" }, 
		{ ["text"] = "b1" }, 
		{ ["text"] = "b2" }, 
		{ ["text"] = "b3" }, 				
	}
end

test:choices(getChoices)

test:rightClickCallback(function()
	test:refreshChoicesCallback()
end)

test:show()
```

I've tried capturing the `:query()` then re-applying it after `:refreshChoicesCallback()`, but that has no impact.

Any ideas @cmsj or @asmagill ?

### PR DESCRIPTION
**Pull request by latenitefilms**
- Updated `hs.chooser:refreshChoicesCallback()` to take into account
the current query string
- Was originally submitted in #1903 however @cmsj needed to revert.
- Closes #1876

### CODE REVIEW

**Comment by latenitefilms** [comment]
Here's some basic test code for anyone who wants to test these changes:

```lua
local chooser = require("hs.chooser")
local console = require("hs.console")
local inspect = require("hs.inspect")
local styledtext = require("hs.styledtext")

local completionFn = function(result)
	print(string.format("Result: %s", result and inspect(result)))
end

local fancyText = styledtext.new("First Choice", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 18 },
    })

local fancySubText = styledtext.new("This is the subtext of the first choice", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 12 },
    })

console.printStyledtext(fancyText)
console.printStyledtext(fancySubText)

local function getChoices()
    return {
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },				
    }
end

theChooser = chooser.new(completionFn)
	:choices(getChoices)
	:rightClickCallback(function() 
	    theChooser:refreshChoicesCallback() 
	    print("refresh!")
	end)
	:show()
```

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - I just tested the above test code, and everything seems to be working fine here? Both shortcut key, manual keyboard selection and mouse selection seems to work as expected?

**Comment by latenitefilms** [comment]
@cmsj - I've merged in the latest `master` code, and this branch still seems to work as expected.

You can use the test code [above](https://github.com/Hammerspoon/hammerspoon/pull/1974#issuecomment-434481586). Type "a" in the chooser, then right-click on the chooser (which will trigger `refreshChoicesCallback()`), and the chooser content should still be correct. If you do this in 0.9.75, triggering `refreshChoicesCallback()` will "reset" the chooser values, and not take into account the current query string.

Using the **CMD+1-9** shortcuts and arrow key selection still seems to work as expected.

Any issues let me know.

**Comment by cmsj** [comment]
Merged, thanks. Hopefully it works for everyone this time :D

**Comment by latenitefilms** [comment]
> Argh, sorry, I had to revert again. It's the arrow key navigation that breaks.

_Originally posted by @cmsj in https://github.com/Hammerspoon/hammerspoon/pull/2138#issuecomment-523418568_

Huh... that's weird. Let me test again here.

**Comment by latenitefilms** [comment]
@cmsj - I can't reproduce the issue you're seeing? Arrow keys seem to work fine on both CommandPost & Hammerspoon using this code?

**Comment by cmsj** [comment]
Sorry yeah, I meant to say I'd reverted this one, not the NSPanel one. Picked the wrong PR to comment on.

I see it when using Seal - pressing up/down just refreshes things and places the selection highlight over the first item.

**Comment by latenitefilms** [comment]
No problemo!

So it seems like Seal is triggering `refreshChoicesCallback()` every time the `queryChangedCallback()` is triggered.

```lua
function obj.queryChangedCallback(query)
    if obj.queryChangedTimer then
        obj.queryChangedTimer:stop()
    end
    obj.queryChangedTimer = hs.timer.doAfter(0.2, function() obj.chooser:refreshChoicesCallback() end)
end
```

Given this, what I think we should probably do then is add an optional variable to `refreshChoicesCallback()` that allows you to `reload`, so that it can take into account the current query string.

Maybe something like this:

```lua
/// hs.chooser:refreshChoicesCallback() -> hs.chooser object
/// Method
/// Refreshes the choices data from a callback
///
/// Parameters:
///  * reload - An optional parameter that reloads the chooser results to take into account the current query string (defaults to `false`)
///
/// Returns:
///  * The `hs.chooser` object
///
/// Notes:
///  * This method will do nothing if you have not set a function with `hs.chooser:choices()`
static int chooserRefreshChoicesCallback(lua_State *L) {
    LuaSkin *skin = [LuaSkin shared];
    [skin checkArgs:LS_TUSERDATA, USERDATA_TAG, LS_TNIL | LS_TBOOLEAN | LS_TOPTIONAL, LS_TBREAK];

    HSChooser *chooser = [skin toNSObjectAtIndex:1];
    
    BOOL reload;
    reload = lua_toboolean(L, 2);

    if (chooser.choicesCallbackRef != LUA_NOREF && chooser.choicesCallbackRef != LUA_REFNIL) {
        [chooser clearChoices];
        [chooser getChoices];
        [chooser updateChoices];
        if (reload) {
            [self controlTextDidChange:[NSNotification notificationWithName:@"Unused" object:nil]];
        }
    }

    lua_pushvalue(L, 1);
    return 1;
}
```

Thoughts @cmsj?

**Comment by cmsj** [comment]
@latenitefilms I think that seems reasonable, yeah.

**Comment by latenitefilms** [comment]
Sweet! Will try do a pull request later today if I get a chance, however feel free to do yourself if you have time to test. I think the above code will work fine - but was written in the browser.

**Pull request closed without merging**
