### PR TITLE
[WIP] Manual/automatic brightness/contrast control of external screens via ddcctl

### PR DESCRIPTION
**Pull request by lowne**
~~needs #688~~

### CODE REVIEW

**Comment by lowne** [comment]
@cmsj (hello!) what are your feelings about this PR? It's missing toggle state persistence, should I work on it?

**Comment by cmsj** [comment]
@lowne I'm still unsure if it's a good idea, but since it has a hard requirement on the installation of an external tool, I think that should be enough of a circuit-breaker to prevent too much user disaster.

**Comment by lowne** [comment]
Not just having it [cloned, compiled and] installed:
```lua
--- hs.brightness.ddcctl
--- Variable
--- In order to use the `hs.brightness.DDC\*` functions, set this to the full path of the `ddcctl` utility (e.g. "/usr/local/bin/ddcctl")
bri.ddcctl=nil
```

>  I'm still unsure

Ok, I'll wait for either :ok_hand: or PR getting closed :)

**Comment by cmsj** [comment]
Ok, I think I'm finished objecting to this :)

**Comment by cmsj** [comment]
@lowne feel free to go ahead with the extras you want to add :)

**Comment by cmsj** [comment]
@lowne I'm going to close this out for now, I suspect you're busy with Hammermoon and other things :)

**Pull request closed without merging**
