### PR TITLE
[DISCUSSION] Created FUNDING.yml

### PR DESCRIPTION
**Pull request by latenitefilms**

### CODE REVIEW

**Comment by cmsj** [comment]
I've typically resisted taking money for this project, because I don't ever want to feel obliged, but that's just my opinion and if either of you (@asmagill and @latenitefilms ) want this to be enabled, I'm happy to go along with it.

**Comment by latenitefilms** [comment]
I can't imagine anyone's going to get rich from adding a "Sponsor" button to this GitHub repo, but I don't think there's any harm in enabling. I think it's a good idea to give people the option to donate some cash if they want to say a quick thanks for helping add a new feature or problem solve an issue.

The pro of GitHub sponsorship is that's it's nicely integrated into the platform. The con is that it's subscription only - so you can't just easily do a one-off payment, which is a turn-off for a lot of people.

We've enabled it on the [CommandPost repo](https://github.com/CommandPost/CommandPost) if you want to have a look.

**Comment by asmagill** [comment]
My concern is that financial contribution often carries with it an implicit implication of *expectation of* or *obligation from* the programmers... my contributions have been as and when I can, and definitely not at the rate they were a couple of years ago... I'm grateful people have found my contributions useful... but my availability is always going to be when its convenient for me and funding isn't going to change that (for me at least). I'm not a commercial programmer for a reason (well, for a lot of reasons, but in this specific case because I want to code what, when, and how *I* want).

**Comment by latenitefilms** [comment]
Completely understand and appreciate your concerns. I definitely don't want to push or expect either yourself or @cmsj to setup GitHub Sponsors if it'll make your Hammerspoon adventures feel like more of a job than a fun little hobby/side-project or if you feel like your under any pressure to spend more time on Hammerspoon. FWIW, even though I'm quite active on this GitHub project and tag you both a lot of issues, I personally never expect any thing from either of you, and know you're just doing it for fun/your own enjoyment.

For me, the little income that I could potentially get from GitHub sponsors will just go towards buying new software/hardware to test and use with Hammerspoon & CommandPost (i.e. I just ordered a Stream Deck XL & Mini to test with Hammerspoon - not because I will personally really use it, but more, that I think having support for these hardware devices is of benefit to the entire Hammerspoon & CommandPost community).

It would be really cool if GitHub allowed you to just contribute a specific amount to a specific issue or pull request, as a "thank you" option.

Either way, I'm fine if you want to merge this pull request, or just close and ignore it - all good either way.

**Comment by cmsj** [comment]
I think I'll close this. I appreciate you raising the discussion, but it seems like neither @asmagill nor I are comfortable with it, and on the assumption that it would raise relatively little money, it seems safer to avoid any potential issues :)

**Comment by cmsj** [comment]
(but to be clear, this isn't a permanent decision - if we want to revisit this later, I'm very happy to do so)

**Pull request closed without merging**
