### PR TITLE
hs.fs.tag additions

### PR DESCRIPTION
**Pull request by asmagill**
addresses #1402

### CODE REVIEW

**Comment by latenitefilms** [comment]
Awesome, thank you!!

**Comment by asmagill** [comment]
May also address #1438

**Comment by asmagill** [comment]
addresses #1400 through applescript wrappers

**Comment by latenitefilms** [comment]
Awesome - thank you!!

**Comment by asmagill** [comment]
addresses #1394

**Comment by latenitefilms** [comment]
Amazing, thanks @asmagill !!

**Comment by asmagill** [comment]
Holding off merge because this is going to cause a merge conflict with #1227 (both modify project.pbxproj)... simple enough to fix, so I'll do both at the same time, but annoying while still tweaking an open pull.

**Comment by cmsj** [comment]
lgtm :)

**Pull request merged**
