### PR TITLE
hs.task - check selfRef validity in stream callback

### PR DESCRIPTION
**Pull request by asmagill**
Ok, my morning appointment got cancelled, so here's a potential fix based on my comments in #1782

### CODE REVIEW

**Comment by joemiller** [comment]
@asmagill If the `task` arg to the callback func is `nil` will there (possibly) be any data in the `stdOut` or `stdErr` args or should the callback always return immediately when `task == nil` ?

**Comment by cmsj** [comment]
@joemiller I suspect the answer right now would be we don’t know. I’ll try and test it shortly and report back.

**Comment by asmagill** [comment]
For a slight variant to the code presented in #1782, I get this in the console:

~~~


> task = hs.task.new("_scratch/foo.sh", function(exitCode, stdOut, stdErr)
	print(string.format("termination rc    : %s", exitCode))
	print(string.format("termination stdOut: %s", stdOut))
	print(string.format("termination stdErr: %s", stdErr))		
end, function(ud, stdOut, stdErr)
	print(string.format("stream ud    : %s", ud))
	print(string.format("stream stdOut: %s", stdOut))
	print(string.format("stream stdErr: %s", stdErr))		
	return true
end):start()

stream ud    : hs.task: _scratch/foo.sh  (0x6080003b3548)
stream stdOut: hello args

stream stdErr: 
stream ud    : hs.task: _scratch/foo.sh  (0x6080003b3548)
stream stdOut: 
stream stdErr: + echo hello args
+ sleep 2

stream ud    : hs.task: _scratch/foo.sh  (0x6080003b3548)
stream stdOut: i am still here 18261

stream stdErr: 
stream ud    : hs.task: _scratch/foo.sh  (0x6080003b3548)
stream stdOut: 
stream stdErr: + echo i am still here 18261
+ sleep 2

stream ud    : hs.task: _scratch/foo.sh  (0x6080003b3548)
stream stdOut: ok i am done now 12438

stream stdErr: 
termination rc    : 0
termination stdOut: 
termination stdErr: 
stream ud    : nil
stream stdOut: 
stream stdErr: + echo ok i am done now 12438
+ exit 0

~~~

So, it looks like the final stream callback (which you'll note is after the termination callback) did contain output... in this case it was the results of the `set -x` command in the script to output each line as it's executed to `stdErr`.

So, my take is that you shouldn't assume that `stdOut` and `stdErr` will be empty, even when the userdata object is `nil`.

**Comment by asmagill** [comment]
It probably depends upon when the task flushes the `stdOut` and `stdErr` buffers... for the sample script I've been using:

~~~sh
#!/bin/bash

set -x

echo hello args $@
sleep 2
echo i am still here $RANDOM
sleep 2
echo ok i am done now $RANDOM
#ls -lR
#exit 1
exit 0
~~~

I commented out the `set -x` line so that the last "output" is the last `echo` command, and running the same test in the console does not invoke the stream callback after the termination callback is invoked.

A few other tests (changing the last `echo` to `echo -n`, redirecting it to `stdErr`, clearing all of the lines after the last echo, including the `exit`) don't change this behavior, so I'm going to make the broad and poorly minimally claim that *most* scripts probably won't ever have this issue unless the shell itself is generating some of the output (like `bash` does when `set -x` is invoked), but that with any compiled task invoked, it's going to depend entirely upon when it's flushing the `stdOut` and `stdErr` buffers -- and if there is anything in one of the buffers when the task terminates that has not been flushed, *that* is when you'll get a stream callback *after* the termination callback.

**Comment by cmsj** [comment]
I haven’t had a moment to test, but I agree with @asmagill’s take. Any process that shares the file descriptors (so, possibly any parent or child process, plus the OS if it feels like it), could write to the file descriptors at basically any time. Fun!

**Comment by joemiller** [comment]
awesome. I hope to try this branch myself tomorrow, or master if it's merged by then. thanks all

**Pull request merged**
