### PR TITLE
Issue #1324 - AppleScript should raise an error if Lua code has errors

### PR DESCRIPTION
**Pull request by latenitefilms**
- Work in progress

### CODE REVIEW

**Comment by asmagill** [comment]
@latenitefilms I haven't been following this line of AppleScript support... can you provide a link or short sample of how I can test it on my end?  I'll do some digging later, but if you have something handy it would save some time.

Thanks!

**Comment by latenitefilms** [comment]
Away from laptop currently but the original issue #1324 should explain everything?

Basically I want AppleScript to trigger an error rather than receiving a text string containing an error message.

**Comment by asmagill** [comment]
Yeah, I understand that it's Hammerspoon being accessed through AppleScript to perform some action... I was hoping for a simple applescript snippit I could run through osascript or a small file I could load into the AppleScript editor to try it out...

AppleScript and I have a love/hate relationship - I love to hate it mostly because I never really took the time to learn it very well and didn't want to have to try and come up with something from scratch...

Ok, I'll bite the bullet in a bit and see what I can come up with.

**Comment by latenitefilms** [comment]
There's an example here: http://www.hammerspoon.org/docs/hs.html#allowAppleScript

**Comment by asmagill** [comment]
SMH! You'd think I would have checked the documentation, wouldn't you?... thanks!

**Comment by latenitefilms** [comment]
@asmagill - FYI: I tried duplicating `MJLuaRunString`, but I keep getting stuck on the following error:

screen shot 2017-09-03 at 8 23 25 pm

Any ideas?

**Comment by asmagill** [comment]
The `evalfn` has to refer to a valid Lua function -- what's currently being pulled from the registry is undefined because `evalfn` is never assigned a value.

For the traditional `MJLuaRunString`, it looks for the second returned argument from `hs/_coresetup/init.lua` (line 566) and assigns it at line 667 of `MJLua.m`

Let me elaborate a little on what I meant in https://github.com/Hammerspoon/hammerspoon/issues/1324#issuecomment-323647668...

The traditional runstring, which is defined in `hs._coresetup` returns a string containing the visual (printed or returned) results of the lua string it is sent to parse.  This returned string is a string ***whether or not it was an error or a valid response***.  Once the string is back in `MJLua.m`, there is **no** possible way to determine if it was generated by an error or by a print statement or by a return statement.

You stated that you wished for the AppleScript integration code to be able to distinguish between a valid response (i.e. print or return) an an error, thus the suggestion that a special runstring function be created and registered for use specifically by the AppleScript integration code so that it *could* determine if a response was valid or not...  But you need to create that runstring command and somehow register it so that it's reference value can be stored in `evalfn` for recall when executing an AppleScript request.

This pull looks like you have some of the infrastructure in place, but you still need to write the lua portion and then register the lua function for use. As for writing the lua portion, take a look at `hs._coresetup`'s init.lua around line 395.  One change I would probably make in the new function is to return two values instead of one (a boolean indicating valid (true) or error (false), and a string containing the results... in the replicated runstring function, line 398 might end `... return false, tostring(err)` and line 406 might be `return results[1], str`)

Of course you'll want to define this new lua function somewhere other than `hs._coresetup` -- you don't want to break everything else by modifying the existing runstring.

**Comment by asmagill** [comment]
@latenitefilms status?

**Comment by latenitefilms** [comment]
Sorry, I was sure I replied!

All looks good to me! Thanks for all your hard work!

**Comment by latenitefilms** [comment]
@cmsj - This is good to go, if you agree.

**Comment by asmagill** [comment]
@cmsj absent any objections from you I'm going to merge this tomorrow.

**Comment by cmsj** [comment]
+1 from me

**Pull request merged**
