### PR TITLE
Added new Stream Deck XL PID

### LINKED ISSUE #3553: New revision of Stream Deck XL with a new PID not supported
It seems that my new Stream Deck XL has a new PID, which as per streamdeck.h is currently not supported by Hammerspoon.
Output from hidapitester:
`0FD9/008F: Elgato - Stream Deck XL`

Please add support for the new revision. I am happy to test it out if needed.

### PR DESCRIPTION
**Pull request by latenitefilms**
- Closes #3553

### CODE REVIEW

**Comment by cmsj** [comment]
Do we know if the hardware has changed at all?

**Comment by latenitefilms** [comment]
I don't believe so, but hopefully @priitohlo can confirm once merged and there's a test build.

**Comment by priitohlo** [comment]
Waiting for that build :)

**Comment by cmsj** [comment]
Annoyingly our nice automated CI for doing new trunk builds, is broken at the moment :(

**Comment by cmsj** [comment]
I'll merge this speculatively and try to get a manual build up shortly.

**Comment by latenitefilms** [comment]
Confirmed this works via a user in CommandPost.

**Pull request merged**
