### PR TITLE
add makeConstantsTable to luaskin builtin lua table `ls`

### PR DESCRIPTION
**Pull request by asmagill**
`ls.makeConstantsTable` will set the metatable on a table and all of its subtables so that typing the table into the Hammerspoon console will display the table contents while preventing changes to the table since it's supposed to contain "constants".

Also modified modules which used a hard coded _makeConstantsTable to use this implementation.

We should consider how we want to document LuaSkin and the luaskin.lua file for developers... the current headerdoc solution seems brittle.

### CODE REVIEW

**Comment by cmsj** [comment]
lgtm

@asmagill I don't have a good answer for surfacing the docs for this, but I'm curious what you meant about headerdoc being brittle? It's perhaps not the nicest thing to be working with, but it gets us integration with Xcode's documentation system (at least the part in the right panel) which I think is a big win.

**Comment by asmagill** [comment]
@cmsj re headerdoc:

I forget that you actually do most of your coding in XCode...

Brittle was maybe too strong a word... My problems with headerdoc (and I'm fine if the ultimate answer ends up being for me to just deal with it, but since I opened up the question...):

* It's inconsistent with the rest of our documentation... there is no docset (not a problem per se, but inconsistent with the Hammerspoon docs and it means I can't use Dash)
* Now that we're looking to add some lua helpers to the LuaSkin framework, we'll either have to have 2 separate docs or replicate a lot of extra comments in Skin.h to get the lua portion documented.
* `headerdoc2html` against the Skin.h file as it is currently written:
~~~
$ headerdoc2html -u -o build/html/LuaSkin LuaSkin/LuaSkin/Skin.h 

Documentation will be written to build/html/LuaSkin
HTML output mode.
======= Parsing Input Files =======

Processing LuaSkin/LuaSkin/Skin.h
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TBREAK The final value in all @link //apple_ref/occ/instm/LuaSkin/checkArgs: checkArgs @/link calls, signals the end of the argument list 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TOPTIONAL Can be OR'd with any argument to indicate that it does not have to be present 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TNIL maps to LUA_TNIL 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TBOOLEAN maps to LUA_TBOOLEAN 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TNUMBER maps to LUA_TNUMBER 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TSTRING maps to LUA_TSTRING 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TTABLE maps to LUA_TTABLE 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TFUNCTION maps to LUA_TFUNCTION 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TUSERDATA maps to LUA_TUSERDATA 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TNONE maps to LUA_TNONE.  Deprecated, as this serves no real use in checkArgs except to provide parity with Lua's LUA_TNONE, which is handled by optional argument tagging or as an argument count error. 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TANY indicates that any Lua variable type is accepted 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TINTEGER Can be OR'd with LS_TNUMBER to specify that the number must be an integer.  This option is ignored if paired with other types. 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TVARARG Can be OR'd with LS_TBREAK to indicate that any additional arguments on the stack after this location are to be ignored by @link //apple_ref/occ/instm/LuaSkin/checkArgs: checkArgs @/link.  It is the responsibility of the module function to check and use or ignore any additional arguments. 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TTYPEDTABLE maps to LUA_TTABLE, but like LS_TUSERDATA, expects a string argument following which specifies the specific value expected in the __luaSkinType field of the table. 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_BREADCRUMB for messages that should be considered for recording in crash logs 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_VERBOSE for messages that contain excessive detail that is usually only of interest during debugging 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_DEBUG for messages that are usually only of interest during debugging 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_INFO for messages that are informative 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_WARN for messages that contain warnings 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_ERROR for messages that indicate an error has occured 
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:271:Unknown field type @code in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:271:Unknown field type @endcode in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:295:Unknown field type @remark in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:313:Unknown field type @remark in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:324:Unknown field type @remark in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:337:Unknown field type @remark in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:386:Unknown field type @remark in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:441:Unknown field type @remark in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:441:Unknown field type @remark in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:472:Unknown field type @remark in HeaderDoc comment.
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:472:Unknown field type @remark in HeaderDoc comment.
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logBreadcrumb:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logBreadcrumb:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logDebug:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logDebug:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logError:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logError:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logInfo:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logInfo:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logVerbose:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logVerbose:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logWarn:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logWarn:/theMessage_DONTLINK_0
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:0: warning: no symbol matching "LS_NSConversionOptions" found.  If this symbol is not in this file or class, you need to specify it with an api ref tag (e.g. apple_ref).
/opt/amagill/src/hammerspoon/hammerspoon/LuaSkin/LuaSkin/Skin.h:0: warning: no symbol matching "LS_NSConversionOptions" found.  If this symbol is not in this file or class, you need to specify it with an api ref tag (e.g. apple_ref).
...done
~~~
* I can get rid of the `unknown field type` errors with the following:
~~~
$ sed -e 's/@code/<pre>@textblock/' \
     -e 's/@endcode/@\/textblock<\/pre>/' \
     -e 's/@remark/@attributeblock Notes/' LuaSkin/LuaSkin/Skin.h > Skin.h
$ headerdoc2html -u -o build/html/LuaSkin Skin.h

Documentation will be written to build/html/LuaSkin
HTML output mode.
======= Parsing Input Files =======

Processing Skin.h
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TBREAK The final value in all @link //apple_ref/occ/instm/LuaSkin/checkArgs: checkArgs @/link calls, signals the end of the argument list 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TOPTIONAL Can be OR'd with any argument to indicate that it does not have to be present 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TNIL maps to LUA_TNIL 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TBOOLEAN maps to LUA_TBOOLEAN 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TNUMBER maps to LUA_TNUMBER 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TSTRING maps to LUA_TSTRING 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TTABLE maps to LUA_TTABLE 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TFUNCTION maps to LUA_TFUNCTION 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TUSERDATA maps to LUA_TUSERDATA 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TNONE maps to LUA_TNONE.  Deprecated, as this serves no real use in checkArgs except to provide parity with Lua's LUA_TNONE, which is handled by optional argument tagging or as an argument count error. 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TANY indicates that any Lua variable type is accepted 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TINTEGER Can be OR'd with LS_TNUMBER to specify that the number must be an integer.  This option is ignored if paired with other types. 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TVARARG Can be OR'd with LS_TBREAK to indicate that any additional arguments on the stack after this location are to be ignored by @link //apple_ref/occ/instm/LuaSkin/checkArgs: checkArgs @/link.  It is the responsibility of the module function to check and use or ignore any additional arguments. 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:39: warning: Found invalid headerdoc markup:  @define LS_TTYPEDTABLE maps to LUA_TTABLE, but like LS_TUSERDATA, expects a string argument following which specifies the specific value expected in the __luaSkinType field of the table. 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_BREADCRUMB for messages that should be considered for recording in crash logs 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_VERBOSE for messages that contain excessive detail that is usually only of interest during debugging 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_DEBUG for messages that are usually only of interest during debugging 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_INFO for messages that are informative 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_WARN for messages that contain warnings 
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:84: warning: Found invalid headerdoc markup:  @define LS_LOG_ERROR for messages that indicate an error has occured 
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logBreadcrumb:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logBreadcrumb:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logDebug:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logDebug:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logError:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logError:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logInfo:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logInfo:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logVerbose:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logVerbose:/theMessage_DONTLINK_0
Warning: UID //apple_ref/doc/methodparam/LuaSkin/logWarn:/theMessage shared by multiple objects.  Disambiguating: new uid is //apple_ref/doc/methodparam/LuaSkin/logWarn:/theMessage_DONTLINK_0
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:0: warning: no symbol matching "LS_NSConversionOptions" found.  If this symbol is not in this file or class, you need to specify it with an api ref tag (e.g. apple_ref).
/opt/amagill/src/hammerspoon/hammerspoon/Skin.h:0: warning: no symbol matching "LS_NSConversionOptions" found.  If this symbol is not in this file or class, you need to specify it with an api ref tag (e.g. apple_ref).
...done
~~~
* Haven't bothered tracking down the rest because the result of the second approach is mostly useful.

I did come across a project called [AppleDoc](https://www.cocoanetics.com/2011/11/amazing-apple-like-documentation/) which looks like it might be able to address some of these issues, but haven't had a chance to dig too deeply... it appears to require a lot of arguments to be set properly and I've not had the time to review its documentation for these in depth yet.  So... my issues may be transitory anyways, but I did open my mouth, so... this is why my not so friendly attitude towards headerdoc 😁

**Comment by asmagill** [comment]
A better link for AppleDoc: http://gentlebytes.com/appledoc/

**Comment by cmsj** [comment]
heh, apparently I'd blocked all of the header2html warnings/errors out of my mind. I'm happy to switch tool if appledoc does a better job of the html.  I feel quite strongly though that the objc docstrings should stay in the Appley format so Xcode integration works properly - that's the expected behaviour of a framework. We can probably do something for Dash with it, I just haven't been motivated to do so because I don't use Dash anymore. Feel free to open an issue about switching :)

(also feel free to land this PR :)

**Comment by junkblocker** [comment]
+1 to keeping Dash support on par. I depend on it and never use XCode :)

**Pull request merged**
