### PR TITLE
[READY] Issues #1644 & #1636 - Adds support for Virtual MIDI Devices in hs.midi

### LINKED ISSUE #1636: hs.midi - Incorrectly returning noteOn when should be noteOff
@asmagill - I'm not sure if this is an issue in `hs.midi` or MIKMIDI 1.6.2, but when I have a MIDI keyboard connected to my computer, when I press a key I'm now seeing two `noteOn` commands, instead of a `noteOn` and `noteOff`.

When I was originally testing things, I was definitely seeing `noteOff` commands - so I'm not sure when/how it broke.

Using the following test code:

```
midiDevice = hs.midi.new(hs.midi.devices()[2]) midiDevice:callback(function(object, deviceName, commandType, description, metadata)
       print("object: " .. tostring(object))
       print("deviceName: " .. deviceName)
       print("commandType: " .. commandType)
       print("description: " .. description)
       print("metadata: " .. hs.inspect(metadata))
end)
```

...gives me:

```
2017-12-30 11:02:05: object: table: 0x60c00046f200
2017-12-30 11:02:05: deviceName: USB O2
2017-12-30 11:02:05: commandType: noteOn
2017-12-30 11:02:05: description: <MIKMIDINoteOnCommand: 0x600000a32e20> time: 11:02:05.068 command: 159 channel 0 note: 25 velocity: 42 
	data: <90192a>
2017-12-30 11:02:05: metadata: {
  channel = 0,
  note = 25,
  timestamp = "11:02:05.068",
  velocity = 42
}
2017-12-30 11:02:05: object: table: 0x60c00046f200
2017-12-30 11:02:05: deviceName: USB O2
2017-12-30 11:02:05: commandType: noteOn
2017-12-30 11:02:05: description: <MIKMIDINoteOnCommand: 0x60400063c360> time: 11:02:05.652 command: 159 channel 0 note: 25 velocity: 0 
	data: <901900>
2017-12-30 11:02:05: metadata: {
  channel = 0,
  note = 25,
  timestamp = "11:02:05.652",
  velocity = 0
}
```

Notice the `<MIKMIDINoteOnCommand: 0x600000a32e20>` and `<MIKMIDINoteOnCommand: 0x60400063c360>` - which makes me think it's maybe a bug in MIKMIDI? Any ideas @armadsen?

### LINKED ISSUE #1644: Add support for virtualSources to hs.midi
See: http://cocoadocs.org/docsets/MIKMIDI/1.6.1/Classes/MIKMIDIDeviceManager.html#//api/name/virtualSources

### PR DESCRIPTION
**Pull request by latenitefilms**
- Adds support for Virtual MIDI Devices in `hs.midi`
- Closes #1644
- Fixes documentation formatting
- Adds note about `noteOff` handling
- Closes #1636

### CODE REVIEW

**Comment by latenitefilms** [comment]
@asmagill & @cmsj - Ok, now unless I accidentally press the wrong button again and merge all of CommandPost into this branch, THIS should now be ready to merge away.

**Comment by latenitefilms** [comment]
I just tried sending a command to a virtual MIDI source and got the following error:

```lua
> midiDevice = hs.midi.newVirtualSource(hs.midi.virtualSources()[2])
midiDevice:sendCommand("noteOn", {
	["note"] = 72,
	["velocity"] = 50,
	["channel"] = 0,
})
NSRangeException: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
(
	0   CoreFoundation                      0x00007fff4cd7d00b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7395bc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4cdbe514 _CFThrowFormattedException + 202
	3   CoreFoundation                      0x00007fff4cc9bdb4 -[__NSArrayM objectAtIndex:] + 148
	4   internal.so                         0x0000000111786740 midi_sendCommand + 950
	5   LuaSkin                             0x000000010a75d920 luaD_precall + 695
	6   LuaSkin                             0x000000010a75be45 luaV_execute + 7345
	7   LuaSkin                             0x000000010a75da76 luaD_call + 64
	8   LuaSkin                             0x000000010a75dab7 luaD_callnoyield + 21
	9   LuaSkin                             0x000000010a7656bb luai_objcttry + 28
	10  LuaSkin                             0x000000010a75df85 luaD_pcall + 116
	11  LuaSkin                             0x000000010a76e588 lua_pcallk + 122
	12  LuaSkin                             0x000000010a76b0ea luaB_xpcall + 115
	13  LuaSkin                             0x000000010a75d920 luaD_precall + 695
	14  LuaSkin                             0x000000010a75be45 luaV_execute + 7345
	15  LuaSkin                             0x000000010a75da76 luaD_call + 64
	16  LuaSkin                             0x000000010a75dab7 luaD_callnoyield + 21
	17  LuaSkin                             0x000000010a7656bb luai_objcttry + 28
	18  LuaSkin                             0x000000010a75df85 luaD_pcall + 116
	19  LuaSkin                             0x000000010a76e588 lua_pcallk + 122
	20  LuaSkin                             0x000000010a752713 -[LuaSkin protectedCallAndTraceback:nresults:] + 203
	21  CommandPost                         0x000000010a413b6e MJLuaRunString + 167
	22  CommandPost                         0x000000010a411a29 -[MJConsoleWindowController tryMessage:] + 153
	23  AppKit                              0x00007fff4aa7175a -[NSApplication(NSResponder) sendAction:to:from:] + 312
	24  AppKit                              0x00007fff4a517933 -[NSControl sendAction:to:] + 86
	25  AppKit                              0x00007fff4a4891a6 -[NSTextField textDidEndEditing:] + 937
	26  CommandPost                         0x000000010a412561 -[HSGrowingTextField textDidEndEditing:] + 42
	27  CoreFoundation                      0x00007fff4cd0ca3c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	28  CoreFoundation                      0x00007fff4cd0c92a _CFXRegistrationPost + 442
	29  CoreFoundation                      0x00007fff4cd0c672 ___CFXNotificationPost_block_invoke + 50
	30  CoreFoundation                      0x00007fff4ccca450 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1664
	31  CoreFoundation                      0x00007fff4ccc9583 _CFXNotificationPost + 595
	32  Foundation                          0x00007fff4edbc3c7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	33  AppKit                              0x00007fff4a5fd77a -[NSTextView(NSPrivate) _giveUpFirstResponder:] + 440
	34  AppKit                              0x00007fff4a4760ff -[NSTextView doCommandBySelector:] + 200
	35  AppKit                              0x00007fff4a476013 -[NSTextInputContext(NSInputContext_WithCompletion) doCommandBySelector:completionHandler:] + 118
	36  AppKit                              0x00007fff4a45755a -[NSKeyBindingManager(NSKeyBindingManager_MultiClients) interpretEventAsCommand:forClient:] + 2898
	37  AppKit                              0x00007fff4acf0523 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.1109 + 360
	38  AppKit                              0x00007fff4acf0352 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke_3 + 79
	39  AppKit                              0x00007fff4a45ed95 -[NSTextInputContext tryHandleEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:] + 92
	40  AppKit                              0x00007fff4acf02d1 __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.1099 + 251
	41  HIToolbox                           0x00007fff4c03eb7e __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_5 + 70
	42  HIToolbox                           0x00007fff4c03da36 ___ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec_block_invoke + 110
	43  AppKit                              0x00007fff4ace8d30 __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke.320 + 580
	44  AppKit                              0x00007fff4a4588eb __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke_2 + 79
	45  AppKit                              0x00007fff4a45886e -[NSTextInputContext tryHandleTSMEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:] + 92
	46  AppKit                              0x00007fff4a4583d1 -[NSTextInputContext handleTSMEvent:completionHandler:] + 1722
	47  AppKit                              0x00007fff4a457ca1 _NSTSMEventHandler + 311
	48  HIToolbox                           0x00007fff4bfe7814 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1541
	49  HIToolbox                           0x00007fff4bfe6b5d _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 374
	50  HIToolbox                           0x00007fff4bfe69d3 SendEventToEventTargetWithOptions + 45
	51  HIToolbox                           0x00007fff4c03ac89 SendTSMEvent_WithCompletionHandler + 389
	52  HIToolbox                           0x00007fff4c03b154 __SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler_block_invoke + 403
	53  HIToolbox                           0x00007fff4c03afb2 __SendFilterTextEvent_WithCompletionHandler_block_invoke + 219
	54  HIToolbox                           0x00007fff4c03acd8 SendTSMEvent_WithCompletionHandler + 468
	55  HIToolbox                           0x00007fff4c03aad7 SendFilterTextEvent_WithCompletionHandler + 233
	56  HIToolbox                           0x00007fff4c03a796 SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler + 290
	57  HIToolbox                           0x00007fff4c03a54a __utDeliverTSMEvent_WithCompletionHandler_block_invoke_2 + 289
	58  HIToolbox                           0x00007fff4c03a3cb __utDeliverTSMEvent_WithCompletionHandler_block_invoke + 405
	59  HIToolbox                           0x00007fff4c03a1b8 TSMKeyEvent_WithCompletionHandler + 636
	60  HIToolbox                           0x00007fff4c039efc __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_4 + 262
	61  HIToolbox                           0x00007fff4c039d17 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_3 + 263
	62  HIToolbox                           0x00007fff4c039a52 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_2 + 288
	63  HIToolbox                           0x00007fff4c0397a8 __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke + 280
	64  HIToolbox                           0x00007fff4c038d9f TSMProcessRawKeyEventWithOptionsAndCompletionHandler + 3433
	65  AppKit                              0x00007fff4acf014d __84-[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:]_block_invoke.1090 + 115
	66  AppKit                              0x00007fff4acef51b __204-[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:]_block_invoke.1016 + 120
	67  AppKit                              0x00007fff4acef384 -[NSTextInputContext tryTSMProcessRawKeyEvent_orSubstitution:dispatchCondition:setupForDispatch:furtherCondition:doubleSpaceSubstitutionCondition:doubleSpaceSubstitutionWork:dispatchTSMWork:continuation:] + 255
	68  AppKit                              0x00007fff4acefb91 -[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:] + 1237
	69  AppKit                              0x00007fff4acef211 -[NSTextInputContext _handleEvent:allowingSyntheticEvent:] + 114
	70  AppKit                              0x00007fff4a45674a -[NSView interpretKeyEvents:] + 209
	71  AppKit                              0x00007fff4a45656e -[NSTextView keyDown:] + 724
	72  AppKit                              0x00007fff4ac0e029 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 5040
	73  AppKit                              0x00007fff4ac0c85c -[NSWindow(NSEventRouting) sendEvent:] + 497
	74  AppKit                              0x00007fff4aa6dfa3 -[NSApplication(NSEvent) sendEvent:] + 2751
	75  AppKit                              0x00007fff4a2ced9d -[NSApplication run] + 812
	76  AppKit                              0x00007fff4a29df1a NSApplicationMain + 804
	77  libdyld.dylib                       0x00007fff7454b115 start + 1
	78  ???                                 0x0000000000000001 0x0 + 1
)

```

**Comment by latenitefilms** [comment]
Discussing here: https://github.com/mixedinkey-opensource/MIKMIDI/issues/226

@asmagill - If you have any ideas, let me know.

**Comment by latenitefilms** [comment]
Forgot to mention, the last commit fixed sending messages to Virtual MIDI Devices, so all good!

**Comment by cmsj** [comment]
@latenitefilms I think I might hold off on this until it's clearer what's going on with your RAM usage :)

**Comment by latenitefilms** [comment]
@cmsj - I don't think this is the cause of the big memory usage, as I haven't noticed any big memory usage when using plain old Hammerspoon - I think we just have sooooooo many extensions in CommandPost.

@asmagill - What do you think?

**Comment by latenitefilms** [comment]
@cmsj - Also, given `hs.midi` is already in Hammerspoon public release, and this pull request doesn't change any of the garbage collection code - I reckon this is probably safe to add, because if there is a problem with `hs.midi` - it'll already be in Hammerspoon's public release. Completely up to you though.

**Comment by cmsj** [comment]
Fair points all round :)

**Pull request merged**
