### PR TITLE
[READY] webview hands off unrecognized schemes to OS

### PR DESCRIPTION
**Pull request by asmagill**
Addresses #668 

This update allows you to specify which URL schemes are to be handled by the WKWebView at the heart of this module.  If the scheme isn't in the list, it is handed off to the OS to handle.

This is probably the more user-friendly approach, but a more secure approach would have been to switch directions: list the schemes we're willing to hand out to the OS; however I didn't think of that until just now.

Preferences on whether it should be a list of schemes to handle (and thus hand off what we don't) or whether it should be a list of what we hand off (and thus attempt to handle what isn't listed, causing an Unrecognized protocol error page when WKWebView doesn't really handle it)?

### CODE REVIEW

**Comment by cmsj** [comment]
Which way around does Safari choose? I suggest we mirror that :)

**Comment by asmagill** [comment]
No idea...

The problem as I understand it is that WKWebView doesn't automatically check registered Application or protocol URLs in the same way that UIWebView or WebView did (supposedly -- I've never used them myself).  Nor have I been able to find a list of "officially recognized" protocolos for the WKebView class, generated or otherwise.

It comes down to do we want to field "why isn't X scheme type handled in the webview itself" or "why do I get unrecognized URL type" questions?

**Comment by asmagill** [comment]
I should add that if we pass off what we don't recognize, the OS might pop up a dialog about not recognizing the URL scheme like this:

screen shot 2015-12-08 at 6 22 41 pm

If we attempt to do it ourself and it fails, we get the error page that led to #688.

I suppose I might be able to patch into the didFailNavigation delegate instead of the didAcceptNavigation one... the delegate method doesn't receive the same arguments, but I think we can still get the URL scheme out of one of them.  That might even remove the need for the new function all together, but the module would no longer ever handle the Unrecognized protocol error, since that would be specifically passed out... must mull and test...

**Comment by asmagill** [comment]
Never mind all that above... moved the hand off to didFailProvisionalNavigation when the error type is NSURLErrorUnsupportedURL; that way we don't have to keep track of recognized versus unrecognized... the OS handles anything that WKWebView doesn't handle first.

**Comment by asmagill** [comment]
Note you can still reject any URL you like with the navigationCallback -- that happens before the didFailProvisionalNavigation message occurs.

**Pull request merged**
