### PR TITLE
add active screen watcher

### PR DESCRIPTION
**Pull request by asmagill**
Addresses #755 

Added new constructor to hs.screen.watcher which includes NSWorkspaceActiveDisplayDidChangeNotification in the notifications watched for.

### CODE REVIEW

**Comment by asmagill** [comment]
@cmsj, this is ready, once the travis issue is addressed... did I do something wrong or is this due another pull (one of yours mentions UI Testing, but I know little to nothing about how that is handled...)

**Comment by heptal** [comment]
The UI testing was disabled because it's currently not very useful and causes more problems than it's worth.

**Comment by asmagill** [comment]
Well, it's causing Travis to fail during pull request test builds.... so, should I ignore it?

**Comment by heptal** [comment]
Yea, seems like they just weren't fully disabled. Safe to ignore as long as UI Test failure is the reason since it'll likely be fixed within the day.

**Comment by cmsj** [comment]
sorry, the travis fix last night didn't fix anything because I did it on the wrong scheme. it is fixed now :)

**Pull request merged**
