### PR TITLE
Added hs.osc extension

### LINKED ISSUE #1580: hs.osc - Add Extension for OSC Control
I'd imagine it interfacing with something like: 

https://hexler.net/docs/touchosc-configuration-connections-osc

Similar reasons for #1422.

Possibly Useful:

https://github.com/lubyk/osc
http://lua-users.org/lists/lua-l/2006-04/msg00408.html

### PR DESCRIPTION
**Pull request by latenitefilms**
- Added `F53OSC` pod, however I had to manually delete `CocoaAsyncSocket` which is bundled with it (as it's already included in Hammerspoon).
- Added `hs.osc` extension.
- Closes #1580

### CODE REVIEW

**Comment by latenitefilms** [comment]
Example Usage:

```lua
-- Define the listening port:
local listeningPort = 9999

-- Set up a table of triggers:
local oscTriggers = {
	["a"] = function(v) print(string.format("We got an A with these variables:\n %s", hs.inspect(v))) end,
	["b"] = function(v) print(string.format("We got an B with these variables:\n %s", hs.inspect(v))) end,
	["c"] = function(v) print(string.format("We got an C with these variables:\n %s", hs.inspect(v))) end
}

-- Setup a new OSC Server:
oscServer = hs.osc.newServer(listeningPort)

-- Setup a callback for the OSC Server:
oscServer:callback(function(obj, addressParts, arguments)
	-- Print a debug message:
	print(string.format([[
		OSC Message Received:
		 - obj: %s
		 - addressParts: %s
		 - arguments: %s
	]], obj, hs.inspect(addressParts), hs.inspect(arguments))) 

	-- Check if the first part of the address is part of our OSC Triggers table:
	local message = addressParts and addressParts[1]
	if oscTriggers[message] then
		oscTriggers[message](arguments)
	end
end)

-- Start the OSC Server:
oscServer:start()
```

You can then use `[sendosc](https://github.com/yoggy/sendosc)` to send a test message via Terminal:

`sendosc localhost 9999 /a s TestString I 123`

**Comment by cmsj** [comment]
Can I be dumb and ask what OSC is? :)

**Comment by latenitefilms** [comment]
@cmsj - Of course! [Open Sound Control (OSC)](https://opensoundcontrol.stanford.edu) is a protocol for networking music devices (like synthesisers, music keyboards, electronic drum kits, etc), multimedia devices (like projectors, etc), lighting control systems, etc. It's basically a better version of MIDI. If you've ever used [TouchOSC](https://hexler.net/touchosc) on iOS/iPad, then that uses both OSC and MIDI.

To be honest, I'm not sure if this is worth including in Hammerspoon (or even CommandPost for that matter), as it's fairly niche - I'm really only playing around with it because someone who's developed a Windows app using OSC, wants to port their code across to macOS, and I think Hammerspoon can basically do everything they need (with this pull request).

Currently I've only added OSC Server support - however, the `F53OSC` framework I'm using has OSC Client support, so it shouldn't be too tricky to add if there's interest.

**Comment by latenitefilms** [comment]
@cmsj - Either way, looks like your CI build script is broken?

```
ERROR: Your active Developer directory is not pointing at Xcode.app. You will need Xcode to build Hammerspoon.
Current Developer path is: /Applications/Xcode_12.5.1.app/Contents/Developer
You can change this with: sudo xcode-select -s /path/to/Xcode.app
Error: Process completed with exit code 1.
```

I saw something similar in Xcode locally at some point.

**Comment by latenitefilms** [comment]
@cmsj - Dumb question... I'm seeing this in Xcode:

image

...but it still compiles and works - it's just autocomplete in Xcode that's broken. I've tried Cleaning the Build folder. Any idea how I can fix?

**Comment by latenitefilms** [comment]
I've added the ability to create an OSC Client as well as a Server. Here's an example:

```lua
-- Define the listening port:
local listeningPort = 9999

-- Setup a new OSC Server:
oscServer = hs.osc.newServer(listeningPort)

-- Setup a callback for the OSC Server:
oscServer:callback(function(obj, addressParts, arguments)
	-- Print a debug message:
	print(string.format([[
		New OSC Message Received!
		 - obj: %s
		 - addressParts: %s
		 - arguments: %s
	]], obj, hs.inspect(addressParts), hs.inspect(arguments))) 		
end)

-- Start the OSC Server:
oscServer:start()

-- Setup a new OSC Client:
oscClient = hs.osc.newClient("localhost", 9999)

-- Start the OSC Client:
oscClient:start()

-- Send a message from the OSC Client to the OSC Server:
oscClient:send("/this/is/a/test", {"string", 123, false})
```

**Comment by cmsj** [comment]
@latenitefilms I'm honestly kinda nervous about this one - mainly because it pulls in another pod, and I agree it seems kinda niche. Any issues if we skip this one for HS?

**Comment by latenitefilms** [comment]
No problemo!

**Pull request closed without merging**
