### PR TITLE
hs.hotkey: add help for setLogLevel and getLogLevel

### PR DESCRIPTION
**Pull request by muescha**
it would be nice to have this methods visible in the documentation

maybe we add a link to hs.logger.setLogLevel and hs.logger.getLogLevel ?

### CODE REVIEW

**Comment by muescha** [comment]
I don't know how to add labels... I don't see labels in the github ui... maybe I don't have a permission to add a label?

**Comment by asmagill** [comment]
On the right side of this conversation, near the top, do you see little gear icons next to labels like Reviewers, Assignees, Labels, Projects, etc? I'm not sure if those options are limited or universally available...

If you do see them, click on the gear icon next to Labels and select from there... I'm guessing (without having really looked too closely at this pull) that it should be a pr-enhancement or pr-fix, but use your judgement.

If not, post here and I can add it for you.

**Comment by latenitefilms** [comment]
Only @asmagill and @cmsj have permissions to add labels.

**Comment by asmagill** [comment]
ah... ok, wasn't sure

**Comment by muescha** [comment]
i can not see the failing test anymore :(

**Pull request merged**
