### PR TITLE
Refactor hs.serial pull #2397

### PR DESCRIPTION
**Pull request by asmagill**
Will replace #2397 

Note to self: when dealing with multiple pulls adding new modules and pods, merge them ***before*** merging a pull that updates existing pods... significantly fewer file conflicts in pbxproj files

@latenitefilms I'll need to do the same for `hs.socket`, but I hope this hasn't made it too difficult for you to keep CP in sync with Hammerspoon once these are done... sorry!

### CODE REVIEW

**Comment by asmagill** [comment]
(I mean hs.websocket)

**Comment by latenitefilms** [comment]
TIP: If you're seeing lots of conflicts in the pods folder, don't be afraid to run `pod update` again to fix things.

**Comment by asmagill** [comment]
If I checkout the pull request (#2397) locally, edit it's Podfile with the updated version numbers for the pods updated in #2450 and #2432 so that the only difference is the new line for ORSSerialPort, run `pod update`, then try to merge that with the current master, it still shows a crap-ton of conflicts in `./Pods/Pods.xcodeproj/project.pbxproj`, most of which are long hash values that are mind numbing to compare and it's not immediately obvious what they refer to...

Or have I missed something somewhere?

Creating this brand new pull was fairly simple and I don't mind doing so again for `hs.websocket`, but I don't know what issues it might cause you in keeping HS and CP relatively in sync... in fact that's why I haven't landed this yet -- if there is a better way I'm open to hearing it...

**Comment by latenitefilms** [comment]
Ummm, there shouldn't be any conflicts because when you run pod update it rewrites those files. I'll try updating my branches with the latest master code, and update the pods, so hopefully it's smoother.

**Comment by asmagill** [comment]
Ok, I thought I posted this already, but it's not appearing here, so I really must be getting tired...

What I wanted to say is that I expected what you said above, but that isn't what I saw... let me know how it goes for you, or I'll try again tomorrow -- I'm going to get some sleep now and finish getting everything release ready tomorrow (well, later today at this point...)

**Comment by latenitefilms** [comment]
In THEORY, the only files you should need to manually fix are:

- `Hammerspoon.xcodeproj/project.pbxproj`
- `Podfile`
- `Podfile.lock`
- `Pods/Manifest.lock`

...then when you run `pod update` it SHOULD fix all the files within the `Pods` folder.

I've just updated #2397.

**Comment by asmagill** [comment]
Yeah, those 4 files needed fixing, but were pretty minor...

To be clear, are you saying that I should discard the merge conflict to `./Pods/Pods.xcodeproj/project.pbxproj`, but make sure to run `pod update` before committing the merge? If it truly is rebuilding `./Pods/Pods.xcodeproj/project.pbxproj` during each update, that would make sense... after all, that was the file that looked insane to try and manually fix.

**Comment by latenitefilms** [comment]
Yes, that's correct - I've never personally touched `./Pods/Pods.xcodeproj/project.pbxproj` - I just let the pod platform handle all that.

**Comment by asmagill** [comment]
closing as I'd rather merge the original request and think I know how to do so now

**Pull request closed without merging**
