### PR TITLE
[WIP] Modernise hs.application, hs.window and hs.uielement

### PR DESCRIPTION
**Pull request by cmsj**
This is definitely not ready yet, it doesn't build and I've only really done hs.application so far, and it's not tested.

Critiques welcome though :)

### CODE REVIEW

**Comment by latenitefilms** [comment]
Sweet! Curious... do these changes bring with it any performance improvements, or is it more just about making all the code more consistent/clean?

**Comment by cmsj** [comment]
@latenitefilms if anything the performance would be slightly worse because more ObjC work is happening, but I would expect the overhead to be pretty minimal. This is really just about dragging these three modules into the future. They're currently very tightly coupled in ways that don't make much sense, and they have had the least attention as we've improved LuaSkin.

**Comment by asmagill** [comment]
@cmsj, I'll try and take a look at it tonight; haven't looked at the code yet -- when you say it definitely isn't ready, any specific things missing? If I merge it into my local build is there anything in particular I should expect it to break or be missing atm?

**Comment by cmsj** [comment]
@asmagill At the time I wrote that, I had a lot of `//FIXME: Implement this` in methods :)

I've just gotten to a point where everything builds/links (although I have had to do some terrible things to make the dynamic linker happy. More on that later) and is just about limping along. Lots of things seem to be broken right now though :)

My general plan here is that I'm going to try and get this to a point where my config runs, and then I'll flip back to `master` and write a load of tests for `hs.application`/`hs.window`/`hs.uielement`, rebase this branch on top of that, and run down all the tests that will start to fail.

At this point I'm really just looking for any commentary about major things I'm doing wrong (e.g. right now the code on github makes the same `selfRef` mistake I made on `hs.streamdeck`. My local copy is now using `selfRefCount` like it should do, and I'll push it up before I step away for the night :)

**Comment by cmsj** [comment]
Ok, there's my current code. The main thing that's broken right now is that the C modules now properly separate module functions and userdata methods, so the various `init.lua` files that are adding methods, are writing them to the wrong place (e.g. `hs.window:moveToUnit()`)

**Comment by cmsj** [comment]
This now feels like it's coming together quite nicely. The one big caveat is that I've had to do a couple of things to make the modernised code actually load:

1) This PR will dynamically link `libapplication.dylib`, `libwindow.dylib` and `libuielement.dylib` into the main Hammerspoon executable. They're not statically compiled into the binary, but this is an extra layer of linkage that will probably make it difficult for someone to override those libraries with their own local versions.
2) `hs.application`, `hs.window` and `hs.uielement` are unconditionally loaded by `hs._coresetup` to ensure that they are all always present.

I'm really not sure how to get around this without lots of really ugly meta-programming. Each of them depends on at least one of the others and unless we try and construct the relevant instantiations with dynamic dispatching (which, to be fair, we have done in other places, but with much lower risk tasks), the only other option I can think of would be to unify them into a single module, so all the ObjC symbols are present in a single dylib.

@asmagill do you have any objections to the above? I think it's probably acceptable to go down this route because those three modules have always been a nightmare of interdependency, and that doesn't really change, they'll just be easier to work with in the future.

**Comment by asmagill** [comment]
When you say "dynamically link into the main Hammerspoon executable" are you talking about listing them as dependencies in XCode's build requirements?  If it's just that they're explicitly loaded in `hs._coresetup`, then we can still override them with a local build because `setup.lua` puts our config paths at the front of `package.path` and `package.cpath` and *then* invokes `hs._coresetup`.

Not ideal, but other then significant updates like the one you're doing now, it's probably a reasonable assumption that these modules don't get modified very often, and you *can* always do a custom build of the Hamemrspoon application, even if it is a little slower to go through multiple iterations during development. I wouldn't waste more effort on it at this stage unless inspiration strikes.

I'll merge this into my code later today and see what/if anything breaks on my end 🤪

**Comment by cmsj** [comment]
@asmagill all of the modules are listed as target dependencies, but that just means they get built before the hammerspoon binary. What I've done is added them into the "Link Binary With Libraries" build phase, which previously just had LuaSkin.framework and libPods-Hammerspoon.a (all the Cocoapods libraries)

**Comment by asmagill** [comment]
I phrased it badly, but that was basically what I was confirming... that they're pre-linked rather then being linked on demand with the `dlopen` in the lua code for `require`.

**Comment by cmsj** [comment]
Didn't make as much progress on this as I hoped over the weekend - the hs.application tests I've been adding, are failing in extremely weird ways (mainly that `hs.application.open()` launches the test apps, but fails to then find them in a way I can't yet reproduce outside of a testing build.

**Comment by cmsj** [comment]
(fwiw, I'm adding the tests on this branch: https://github.com/cmsj/hammerspoon/tree/add-tests-application-window-uielement )

**Comment by asmagill** [comment]
I've downloaded it for review, but haven't compiled it yet... I'll let you know my observations when I do.

@latenitefilms, if/when you try out this branch, `hs._asm.axuielement` will break. The version I'm working on right now which (fingers crossed) will support observers *should* detect which version of the application/window initializers it should use, but this isn't well tested yet.

**Comment by latenitefilms** [comment]
@asmagill - Awesome! I'm REALLY excited to test out the new `hs._asm.axuielement` release! Keep me posted when it's ready for testing!

**Comment by cmsj** [comment]
@asmagill I've not had a chance to look at `axuielement`, but while rewriting these three modules it did occur to me that they're sufficiently similar under the hood that it might make sense to unify the objc sides at some point, such that the `HSapplication` and `HSwindow` classes are subclasses of `HSuielement`.

**Comment by asmagill** [comment]
Ok, @latenitefilms, have at it: https://github.com/asmagill/hs._asm.axuielement

@cmsj, at one point I thought about whether or not `hs._asm.axuielement` could replace or at least extend `hs.uielement` (and thus `hs.application` and `hs.window` as well), but I'm no longer in favor of that, at least not in any kind of short term... `hs.application` and `hs.window` are probably the core staples of Hammerspoon, at least for new users (well, maybe add `hs.hotkey` too) and need to be solid and simple.  My module is anything but, and even though I consider it approaching stable (at least before tonights additions), simple it is not... but it does provide a way, though not necessarily a simple one, to do things not otherwise even possible with Hammerspoon.

As to whether combining `hs.uielement`, `hs.application`, and `hs.window` (or at least subclassing them) would make things easier or cleaner, I leave that to your discretion... I can certainly see some benefit to thinking of the three as one module with two (three?) different faces. And while you can sort of use `hs.application` without `hs.window` (as an app launcher for example), the opposite can't be said... you have to get the window from somewhere. So even if we still care at some level about minimizing dependancies and memory, these three are not where I would worry about it.

**Comment by latenitefilms** [comment]
@asmagill - Woooohooo! Will let you know how we go!

**Comment by asmagill** [comment]
@cmsj, adding this to my current local version (which admittedly has a few things not in master yet in it) causes Hammerspoon to crash on startup -- should I look into why (i.e. figure out what is different a bout my setup) or is this out of sync with some of your more recent changes (logging updates, 0.9.59, etc.)?

**Comment by cmsj** [comment]
Hmm, it shouldn’t be any of the more recent changes. Could you paste a backtrace?

**Comment by asmagill** [comment]
When built from the command line, it crashes:

~~~
Running Hammerspoon built from command line:


Process:               Hammerspoon [3774]
Path:                  /Applications/Developer/Hammerspoon.app/Contents/MacOS/Hammerspoon
Identifier:            org.hammerspoon.Hammerspoon
Version:               0.9.59 (0.9.59)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Hammerspoon [3774]
User ID:               501

Date/Time:             2018-02-01 03:21:38.208 -0600
OS Version:            Mac OS X 10.13.4 (17E139j)
Report Version:        12
Anonymous UUID:        C6FECEA6-7A66-C651-C0C3-BA6F4083573E


Time Awake Since Boot: 5700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libapplication.dylib
  Referenced from: /Applications/Developer/Hammerspoon.app/Contents/MacOS/Hammerspoon
  Reason: image not found

Binary Images:
       0x10c103000 -        0x10c5c6fef +org.hammerspoon.Hammerspoon (0.9.59 - 0.9.59) <7A5E96B1-D1AC-3D95-8D1E-500BB52EE2C1> /Applications/Developer/Hammerspoon.app/Contents/MacOS/Hammerspoon
       0x10c7ad000 -        0x10c98afe7 +org.hammerspoon.LuaSkin (1.0 - 1) <C1D0B42D-4DF6-3726-B1A6-245E2FFE588F> /Applications/Developer/Hammerspoon.app/Contents/Frameworks/LuaSkin.framework/Versions/A/LuaSkin
       0x116963000 -        0x1169ada3f  dyld (551.3) <526B3FB3-39DE-35B3-99EC-59BE10D53733> /usr/lib/dyld
    0x7fff49aec000 -     0x7fff49d79ff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <60484731-E297-377D-88E7-B70A7C46F1D7> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff49d7b000 -     0x7fff49d7bfff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <3C5ACEF8-E4A8-305E-AD5B-AA609F7A1028> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff4a09a000 -     0x7fff4a433ff7  com.apple.CFNetwork (897.9 - 897.9) <30E99688-9FCF-38C9-94DF-5DA451414824> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff4bf18000 -     0x7fff4bf5dfff  com.apple.audio.midi.CoreMIDI (1.10 - 88) <E7832C94-561A-37CB-8F04-1167A7A11E9D> /System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI
    0x7fff4c30d000 -     0x7fff4c30dfff  com.apple.CoreServices (822.26 - 822.26) <EEC915F1-05FD-3F24-BE58-2907588E7D5A> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff4d301000 -     0x7fff4d6c8fff  com.apple.Foundation (6.9 - 1452.16) <FB02950D-458C-3E90-8EE9-3A5ACB6E2E1C> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff5730b000 -     0x7fff57630fff  com.apple.security (7.0 - 58286.50.176.100.1) <46CD1ED5-278F-3C65-96D8-8060997976F2> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff57a98000 -     0x7fff57b08ff3  com.apple.SystemConfiguration (1.17 - 1.17) <B586BEF4-6B0B-37AC-8693-3903EAC3BCB0> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff713cd000 -     0x7fff713ceffb  libSystem.B.dylib (1252.50.4) <832CE756-D0FF-33C2-90F6-D5BED9FE5ABC> /usr/lib/libSystem.B.dylib
    0x7fff71602000 -     0x7fff71658fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff7337e000 -     0x7fff73465fff  libxml2.2.dylib (31.8) <89523EF1-4496-38E4-B8AB-82E9530F344A> /usr/lib/libxml2.2.dylib
    0x7fff7348f000 -     0x7fff734a1ffb  libz.1.dylib (70) <48C67CFC-940D-3857-8DAD-857774605352> /usr/lib/libz.1.dylib
~~~

It will run within XCode, but copying the version built within XCode to my application directory and running it from there outside of XCode gives the same crash log.

**Comment by cmsj** [comment]
Huh, wow. Thanks - I'll dig into it.

**Comment by asmagill** [comment]
Running from within XCode, I get 

~~~
2018-02-01 03:41:38: ********
03:41:38 ERROR:   LuaSkin: hs.timer callback error: ...oon.app/Contents/Resources/extensions/hs/window/init.lua:515: ERROR: incorrect type 'no value' for argument 2 (expected boolean)
stack traceback:
	[C]: in method '_bringtofront'
	...oon.app/Contents/Resources/extensions/hs/window/init.lua:515: in method 'focus'
	/Users/amagill/.config/hammerspoon/init.lua:122: in function </Users/amagill/.config/hammerspoon/init.lua:120>
2018-02-01 03:41:38: ********
~~~

The timer is defined as:
~~~lua
timer.doAfter(1, function()
    if fmW then
        fmW:focus()
    else
        local finder = application("Finder")
        if finder then
            alert("Activating Finder")
            finder:activate()
        end
    end
end)
~~~
where `fmW` is captured at the beginning of my init.lua as the front-most-window; I've verified that it is defined (not nil) at this point.

Digging into the source for `hs.window` and `hs.application`, you either need to add a boolean flag to line 515 of `hs.window`'s init.lua or give `hs.application`'s `_bringtofront` a default and allow the boolean to be optional. Since it appears to be an internally used function only, I leave the choice to you.

**Comment by cmsj** [comment]
@asmagill @latenitefilms 

I've been trying to revive this PR recently. I'm pretty sure that hs.application and hs.window are close to being done, but I'm less sure about hs.uielement.

It's working fine (as far as I can tell) for all the API that I make regular use of, but I think it could use some wider testing. I can imagine that @asmagill might not want to stray too far from `master` with his coroutine branch testing, but maybe @latenitefilms you could give it a run around the block and see what breaks? I imagine you'll quickly find some uielement stuff if nothing else.

**Comment by latenitefilms** [comment]
No problemo! Will merge into CommandPost and see what explodes.

I don’t think we actually use `hs.uielement` anywhere unless it’s used internally by a Hammerspoon extension.

**Comment by cmsj** [comment]
@asmagill @latenitefilms the code coverage isn't quite as high as I'd like yet, but this is now passing more tests than master is, so I'm probably going to merge it in the next day or two.

Would be super appreciated if y'all could give it a go when I do, because I'm sure there will be tests we don't have, that would have highlighted porting mistakes I've made :)

**Comment by latenitefilms** [comment]
@cmsj - Any chance you could merge in the `coroutine` stuff first? I currently have the `coroutine` branch merged into CommandPost, so ideally if the `coroutine` stuff was also in this branch, it'll make merging the two heaps easier?

**Comment by cmsj** [comment]
@asmagill wrt @latenitefilms 's question - how ready is the coroutine stuff?

**Comment by asmagill** [comment]
@cmsj:
* see https://github.com/Hammerspoon/hammerspoon/pull/2308#issuecomment-600976374
* and https://github.com/Hammerspoon/hammerspoon/pull/2308#issuecomment-602459459

I'm ready to go with it, but have been waiting for your thoughts and comments and review.

**Pull request merged**
