### PR TITLE
Migrate from Crashlytics to Sentry

### PR DESCRIPTION
**Pull request by cmsj**
Crashlytics is now officially shut down. Rather than switching to Google Firebase, I'd like to use Sentry because it's open source and not Google.

TODO:

- [x] Update Privacy Policy
- [x] Turn off as much tracking as possible on sentry.io
- [x] Breadcrumb logging
- [x] Key/Value storage
- [x] Invite @latenitefilms 
- [x] Invite @asmagill

### CODE REVIEW

**Comment by latenitefilms** [comment]
I've just set up a Sentry account for CommandPost in anticipation! :)

**Comment by cmsj** [comment]
Crash reports are working, but I still need to look into the Key/Value and logging parts. Also I need to do a thorough review of Sentry’s “session” tracking to make sure we minimise the amount of user data we collect. Finally, I need to update our Privacy Policy to reflect the differences between Crashlytics and Sentry.

**Comment by cmsj** [comment]
Oh, and I need to invite @latenitefilms and @asmagill to the Sentry team :)

**Comment by cmsj** [comment]
Ok, this is all taken care of and ready to land. The Privacy Policy changes are staged in my local website repo, and will appear automatically on hammerspoon.org when I next do a release.

**Comment by latenitefilms** [comment]
Anything I need to know once I merge this code into CommandPost? Any setup tricks or gottchas?

**Comment by cmsj** [comment]
@Latenitefilms should be pretty easy, the token is the whole DSN URL they give you. The other thing to note is that you can ask them to turn your free account into an open source project sponsored account :)

**Comment by latenitefilms** [comment]
@cmsj - So just to confirm, in the `tokin-sentry` file you should have:

```
SENTRY_API_URL=the long DSN URL
SENTRY_AUTH_TOKEN=the generated token
```

...correct?

**Comment by latenitefilms** [comment]
For anyone playing along at home, yes, the above is correct.

Now working! Yay!

**Pull request merged**
