### PR TITLE
client websockets in hs.http

### PR DESCRIPTION
**Pull request by heptal**
Adds websocket client to `hs.http`, enabling communication with realtime APIs such as Slack.

```lua
> function callback(message)
  print(message) 
end

> url, payload = 'https://slack.com/api/rtm.start', "token="..hs.settings.get('slackKey')
hs.http.asyncPost(url, payload, headers, function(status, response, headers) 
  slack = hs.http.websocket(hs.json.decode(response).url, callback) 
end)

-- Loading extension: http
-- Loading extension: json
15:27:35    LuaSkin: (secondary thread): Client websocket opened
{"type":"hello"}
...

> slack
hs.http.websocket: mpmulti-7rna.slack-msgs.com (0x60800027dde8)

> slack:close()
hs.http.websocket: disconnected (0x60800027dde8)
15:27:56    LuaSkin: (secondary thread): hs.http.webSocket: didClose: (null)
```

### CODE REVIEW

**Comment by cmsj** [comment]
@asmagill any objections to this? I'm ok with it

**Comment by asmagill** [comment]
@cmsj, no objections

**Comment by asmagill** [comment]
@heptal, Can't believe I missed this... the websocket function isn't documented for hs.http.websocket... since we're hoping to get a new release out soon, can you take care of this since it's your creation?

**Comment by heptal** [comment]
Don't know how I missed that! On it.

**Pull request merged**
