### PR TITLE
Added support for Stream Deck Mini V2

### LINKED ISSUE #3377: Add support for latest Stream Deck Mini (20GAI9902)
Reported by @Badsheep in #1686.

### PR DESCRIPTION
**Pull request by latenitefilms**
- Currently untested. Uses same code as Stream Deck Mini, just changing the product ID.
- Closes #3377

### CODE REVIEW

**Comment by latenitefilms** [comment]
@Badsheep - Are you able to build Hammerspoon locally to test this out?

**Comment by cmsj** [comment]
@latenitefilms we could just initialise the existing Mini class, if there's no actual changes required?

**Comment by latenitefilms** [comment]
@cmsj - Yes, I reckon we probably can, however, I went with this way for now, as I'm thinking they've probably changed how it works to be more like the other newer models, so I'm anticipating we might need to tweak some things. I haven't had a chance to do some Googling to see how other open source libraries handle these newer devices yet.

**Comment by Badsheep** [comment]
> @Badsheep - Are you able to build Hammerspoon locally to test this out?

No I’m sorry

**Comment by latenitefilms** [comment]
This isn't signed or notarised, so you might have to right-click to open, but give this a shot:

[Hammerspoon.zip](https://github.com/Hammerspoon/hammerspoon/files/10693051/Hammerspoon.zip)

**Comment by Badsheep** [comment]
> This isn't signed or notarised, so you might have to right-click to open, but give this a shot:
> 
> [Hammerspoon.zip](https://github.com/Hammerspoon/hammerspoon/files/10693051/Hammerspoon.zip)

Sorry it doesn't seems to open :
Capture d’écran 2023-02-09 à 08 00 54

**Comment by Badsheep** [comment]
If I right click, open the Hammerspoon app directly, I have : 

Capture d’écran 2023-02-09 à 08 01 33

**Comment by latenitefilms** [comment]
Ah, apologies, I must have only built it for Apple Silicon.

**Comment by Badsheep** [comment]
Yes I own a intel-based MBP

**Comment by Badsheep** [comment]
Hello, I did test on my girlfriend's Silicon Macbook  : it works.
Of course I haven't tested all the API functions and methods... only hs.streamdeck:setButtonImage(button, image), which seems to work.

Of course I'd be very interested in a Intel built so I can work on my computer ;)
Thanks you very much !

**Comment by latenitefilms** [comment]
Try this one:

[Hammerspoon.zip](https://github.com/Hammerspoon/hammerspoon/files/10706120/Hammerspoon.zip)

**Comment by Badsheep** [comment]
Yes it works :)
Thank you !

**Comment by latenitefilms** [comment]
Awesome! Can you try this one. It's exactly the same, but I've removed the `HSStreamDeckDeviceMiniV2` files, and we're just using the `HSStreamDeckDeviceMini` files as @cmsj suggested.

[Hammerspoon 2.zip](https://github.com/Hammerspoon/hammerspoon/files/10706274/Hammerspoon.2.zip)

**Comment by Badsheep** [comment]
OK, it seems to work too !

**Comment by cmsj** [comment]
Nice!
@latenitefilms the diff for this PR still has the V2 .m/.h files showing up in the project file, otherwise I'm happy for this to merge.

**Comment by latenitefilms** [comment]
@cmsj - My bad, I deliberately didn't push changes to the Xcode project, as I had to make some other tweaks to make it build for Intel machines. Fixed!

**Comment by Badsheep** [comment]
Hello,

Sorry to come back on this case !
But I may have found a bug on the latest release (0.9.100) ? Or maybe it' been introduced before, I don't really know.

When I run the test version you gave two months ago (in the post [above](https://github.com/Hammerspoon/hammerspoon/pull/3378#issuecomment-1425575089)), everything works.

But when I install the last version (0.9.100), the first button (on the top and on the left) doesn't works anymore.
That's the only one not working... the other I use are working.

But it's not completely broke : in my configuration, the image of the button changes depending on the status of the fonction (ON or OFF). And with the new version, the Stream Deck Mini RECEIVES the status (and the images changes correctly), but when I press the button it doesn't change On/Off...

(I hope I'm clear).

**Comment by latenitefilms** [comment]
That's very strange. I'm away for a couple of weeks, but will try and reproduce when I'm back in the office.

**Comment by Badsheep** [comment]
Yes it's strange.
I can send you my .hammerspoon configuration if it helps to debug.

**Comment by Badsheep** [comment]
If you want I can also try all the version between the one you made for me and the actual, and tell you at which version the bug is introduced.

**Comment by Badsheep** [comment]
Hello,

Sorry to bring this thread back to life, but I tried with the last version of Hammerspoon (1.0.0) and the [bug described above](https://github.com/Hammerspoon/hammerspoon/pull/3378#issuecomment-1500661989) is still present : the first button (on the top and on the left) doesn't works anymore.
That's the only one not working... the other I use are working.
I use a Stream Deck Mini v2.
So I'm still using the [custom version you did to me 2 years ago](https://github.com/Hammerspoon/hammerspoon/pull/3378#issuecomment-1425549414)...

**Pull request merged**
