### PR TITLE
additions to hs.chooser

### PR DESCRIPTION
**Pull request by asmagill**
Adds optional row parameter to `hs.chooser:selectedRow` per #1113 
Adds `hs.chooser:selectedRowContents` per #1058 

@cmsj, you should probably take a look at this... I tested this against a static table of items, but I know chooser has options for a dynamically generated list... I *think* it should work, but I haven't had a chance to build one yet.

### CODE REVIEW

**Comment by asmagill** [comment]
@cmsj, when manually changing the query with `hs.chooser:query` it does not affect the items being displayed if the chooser is currently visible, and when the choices array is invalidated with `hs.chooser:refreshChoicesCallback` it resets the list to the entire (new) list, ignoring the current query string (again, if visible, when this is called).

(a) is this intended? if so, educate me please, since I'm missing the reason
(b) would calling `[chooser controlTextDidChange:nil]` at the end of `query` and after the choices callback completes be sufficient to address this?
(c) should it be added or made an option? or completely left as is?

**Comment by asmagill** [comment]
For cabric #468:

hs.chooser isn't validating types of keys in dictionary used to generate list... should either force text and subtext to be string (and image to be image) or coerce when not.

Will add to this pull tonight when I have the time.

**Comment by asmagill** [comment]
@cmsj, can you take a look at this pull, specifically my first two comments, when you get a chance?  I'd like to start landing the currently outstanding pulls and I need your input on these points to know if this specific pull is ready or needs more work.

**Comment by cmsj** [comment]
@this PR looks fine, and I don't think it will break dynamic choice lists.

As for your questions - those behaviours are not intended, and I think (b) should do the trick. I also just noticed that `:query()` doesn't have/document an easy way to clear the search query. Setting it to `""` is probably sufficient, but we don't mention that, and it might be nicer to be able to pass a `nil`.

Sorry for the delay in checking this PR, and thanks!

**Comment by junkblocker** [comment]
Umm, something is broken on HEAD and maybe dynamic choice lists ARE broken. I press a single character and ``queryChangedCallback`` gets called umpteen times. Code for reference is ventolin's notes module from https://github.com/Hammerspoon/hammerspoon/issues/782 .

**Comment by cmsj** [comment]
@junkblocker can you try with this patch applied? I think these are the two lines that are causing the potential for loops:

```
diff --git a/extensions/chooser/HSChooser.m b/extensions/chooser/HSChooser.m
index 69c5aff..277b719 100644
--- a/extensions/chooser/HSChooser.m
+++ b/extensions/chooser/HSChooser.m
@@ -380,7 +380,7 @@ - (void)selectPreviousChoice {
 #pragma mark - Choice management methods

 - (void)updateChoices {
-    [self controlTextDidChange:[NSNotification notificationWithName:NSControlTextDidChangeNotification object:nil]] ;
+    //[self controlTextDidChange:[NSNotification notificationWithName:NSControlTextDidChangeNotification object:nil]] ;
     if (self.window.visible) {
         [self.choicesTableView reloadData];
     } else {
diff --git a/extensions/chooser/internal.m b/extensions/chooser/internal.m
index 21bac7a..2677082 100644
--- a/extensions/chooser/internal.m
+++ b/extensions/chooser/internal.m
@@ -259,7 +259,7 @@ static int chooserSetQuery(lua_State *L) {
                 lua_pushnil(L);
                 break;
         }
-        [chooser controlTextDidChange:[NSNotification notificationWithName:NSControlTextDidChangeNotification object:nil]] ;
+        //[chooser controlTextDidChange:[NSNotification notificationWithName:NSControlTextDidChangeNotification object:nil]] ;
     }
     return 1;
 }
```

**Comment by junkblocker** [comment]
Yes @cmsj, that seems to fix it. Thanks!

**Comment by cmsj** [comment]
@junkblocker thanks!

@asmagill I'm going to apply that partial reversion patch, I think we should probably leave things as they are in this regard - users should be able to determine when it's safe for them to call `:refreshChoicesCallback()`

**Comment by asmagill** [comment]
@cmsj, how hard would it be to setup a "beta" track for releases?  This isn't the first time we've had to make a quick reversion because of changes which work in 90% of the cases, but not in that final 10% that no tester can always check out fully.  And unit testing only works if you know of an issue to test for; it's more suited to make sure future changes don't break things already working rather than testing every use case of something new... and considering we're doing more and more things with async threads and callbacks... well sometimes I'm at a loss for even *how* to build a certain type of test, though that may just be a lack in my knowledge that could be addressed by a tutorial or good reference.

In general I do like to leave a pull up for a few days (except for right before a release), but that relies on our end-users being able and willing to build their own local copies of Hammerspoon... it would be quicker and easier (for them) if some of our users could toggle a checkbox or a flag with `hs.setting` and get early releases for testing...

I don't know anything about Sparkle, so I don't know if this is a something relatively easy to add once we figure out the proper setup on github wrt to branches, etc., but I do think it's an idea worth considering.

**Comment by latenitefilms** [comment]
@asmagill & @cmsj - On this note, if doing a "beta" track is too tricky, what would be really helpful is having a **build** folder in Master, that's always up-to-date. So for example, if @asmagill makes a tweak to `hs.chooser` and merges the changes with the Master, rather than having to build locally, or wait until a public release, we could just grab the "latest" build from the build folder. Thoughts?

**Comment by cmsj** [comment]
@asmagill yeah I know the beta thing keeps coming up. I do like the idea, but I'm not super thrilled with the overhead. I'll open up a new issue and braindump what I think we'd need to do, to make it work.

**Pull request merged**
