### PR TITLE
Streamline Frameworks, Pods, and Build Settings

### PR DESCRIPTION
**Pull request by heptal**
See #810 

Passes all tests! 😁 (Except for that audio one due to float)

Edit: Having some trouble with LuaSkin on a pristine build in Travis. It works perfectly on fresh checkouts on my local machine.

### CODE REVIEW

**Comment by cmsj** [comment]
So, I think this is an excellent idea, but as with #747 I have serious concerns about landing it while we have no test suite. It's become fairly normal to spend a couple of releases tidying up regressions from a previous large change, because we can't detect the things we've broken very easily.

How about we keep this as WIP until we've gotten the test suite more fleshed out? (which I know is my responsibility, and I am moving slowly on, I am suffering for time at the moment)

**Comment by cmsj** [comment]
(and I realise that by not landing it immediately, we'd be pretty much forced into doing the work all over again)

**Comment by heptal** [comment]
It's alright, I've had to scriptify the process to even do it in the first place

**Comment by heptal** [comment]
Closing this one for now. Separating into one for moving crashlytics to podfile and will do another one for xconfig stuff later.

**Pull request closed without merging**
