### PR TITLE
[READY] Fixed bug in hs.fs.urlFromPath()

### PR DESCRIPTION
**Pull request by latenitefilms**
Some paths with non-alphanumeric characters (such as single quotation marks) could break this function - it would return a URL string, but the result wouldn’t be valid for `hs.pasteboard.writeObjects({url=path})` for example. I assume it’s because of the `UTF8String`.

### CODE REVIEW

**Comment by asmagill** [comment]
How certain/close are you the you've caught the edge cases you care about with urls and paths now? Should I wait a bit before testing and merging this?

**Comment by latenitefilms** [comment]
I've now tested this with a whole bunch of random strings, and I can't break it, so I THINK it's all good to merge. I pushed out a public beta of CommandPost last night, and got feedback back pretty quickly that it was broken, and this fix seems to solve those complaints.

We now just use `realpath([filePath stringByExpandingTildeInPath].UTF8String, NULL)` to check the file exists - so there's no longer any conversion happening - it's all `NSString`.

**Comment by asmagill** [comment]
I'm going to wait until morning (my time) just to be certain... but it lgtm.

**Comment by asmagill** [comment]
Ok, so not morning, but it's in there now 😜

**Pull request merged**
