### PR TITLE
WIP: hs.styledtext

### PR DESCRIPTION
**Pull request by asmagill**
I'm not quite ready for it to go live yet, as I'm tracking down an intermittent crash and working up some documentation for it, but if you're interested and don't mind experimental...

This incorporates the X11 colors from #611, the enhanced hs.drawing.color of #602 (and the changes to hs.image, etc. to use LuaSkin rather than hammerspoon.h for creating image objects), and provides an ANSI color converter as requested in #597.

### CODE REVIEW

**Comment by asmagill** [comment]
With these additions, anyplace that uses LuaSkin to get a color (I've updated menubar, drawing, and image here, and I know I need to update my third party console module... are there others?) can accept a table of { red=, blue=, green=, alpha= } or { hue=, saturation=, brightness=, alpha= } or { list=, name= } (for OS X's system color lists), but the list and name fields only work for the system color lists, not for the collections we add to `hs.drawing.color`.  Currently a lua side defined color has to be retrieved via `hs.drawing.color.colorFor("list").name` (this latter also works for the system lists)...

Should the { list=, name= } approach support the collections as well?  My leaning is yes, but it's not quite as simple, since they're defined in Lua and not available via a simple Objective-C method directly...

Thoughts?  Should I add this before adding the pull?  Or is documenting the difference sufficient?

**Comment by cmsj** [comment]
@asmagill being able to access the collections that way sounds nice, but I don't think we need to go crazy to add that

**Comment by lowne** [comment]
@asmagill there's always the possibility of a thin lua wrapper for these conveniences - see also my request in #494

**Comment by asmagill** [comment]
the problem with just accepting an array of numbers is what are they?  RGB? HSB?

What is 1 number? 2?  Since we now allow lists with names, should 2 strings be allowed?  1 and default to the "Apple" list for lookups?

I forgot to mention above that { white=, alpha=} is also allowed... basically the generic's in the NSColor class.  I go back and forth about adding CMYK; since it's in NSColor as a device specific color space, I've avoided it for now, but from past experience, I know that someday I'll probably want it... especially if someone ever decides to tackle a module that can print.

But that would add a possible confusion for 4 numbers as well.

My general feeling is that the keys should be required, even if it does make it a little longer to type since its clear what is intended, but... I'll go with the consensus, so vote!  Vote early, vote often!

And as for the lookups into the collections, the latest pull adds it... I was mainly dreading dealing with possible loops, but I think I addressed that cleanly enough.

**Comment by asmagill** [comment]
I think this is ready to land, pending any last minute requests/changes...

For testing, I primarily used the file at https://gist.github.com/asmagill/3f7f08e5934c4327db3e saved to my desktop as `test.sh`.  Then:

~~~lua
> c = hs.styledtext.ansi(hs.execute("~/Desktop/test.sh"), {font={name="Menlo",size=10}, color={list="Apple",name="White"}, backgroundColor = {alpha=.5}})
> a = hs.webview.new({x = 100, y = 200, h = 70, w = 330}):html(c:convert()):show()
> b = hs.drawing.text({x = 100, y = 100, h = 70, w = 330}, c):show()
~~~

Rendered:

screen shot 2015-10-29 at 10 07 15 pm

**Comment by asmagill** [comment]
In addition, I am in the process of writing a couple of documents which I will add to the Wiki... a more "how do I do..." approach to modifying style with this module, rather than just the built in documentation, and a developers guide/example of how to use `hs.styledtext` in your C module without having to re-invent everything... this later may also serve as an explanation of how the LuaSkin converters work, depending upon how generic it is... or maybe that will be a third document; however, these shouldn't hold up inclusion of this module in the app.

**Comment by lowne** [comment]
Keys 1..4 should mean RGB[A]. Even if the documentation didn't spell it out (and why shouldn't it), I don't see how anybody would think that a color-from-array constructor would default to HSB or CMYK or any other colour space over RGB - without precluding the possibility of allowing said color spaces with named keys.

**Comment by lowne** [comment]
Alternatively, something like this will do:
`function RGBAColor(c) return color{red=c[1],green=c[2],blue=c[3],alpha=c[4]} end`
and I suppose it'll just be used everywhere, even without the dict/list polymorphism (because, why would people want to use the dict anyway)

**Comment by asmagill** [comment]
I'm still not seeing the benefit of brevity in this case - it limits thinking to one color model when others may make more sense programmatically, depending upon what your use case is.

However, if you want to add it, or if there is enough demand, it would only require modifying the `table_toNSColorHelper` function in extensions/drawing/color/internal.m and possibly `NSColor_tolua`, if you want to change what is returned when an Objective-C NSColor object is queried.

For now, I'm going to apply this and it can always be updated later.

**Comment by zzamboni** [comment]
@asmagill I compiled Hammerspoon with these changes, and your example works fine. Thanks!

Unfortunately, some of my old configurations were causing Hammerspoon to crash. I eventually tracked it to my use of `setTextStyle()`. In particular, this statement causes the crash: `text:setTextStyle({ ["alignment"] = "center", ["size"]=16.0})`.

I assume the arguments of `setTextStyle()` have changed, but it would be nice if old-style calls continued to work, or at least didn't cause a crash.

**Comment by asmagill** [comment]
They were supposed to (be silently accepted and not crash), and my test set worked...  apparently I missed something!  I'll take a close look at it today.

Thanks!

**Comment by asmagill** [comment]
@zzamboni , this is fixed in #625. I have a couple of more things I'm tracking down and then I'll add that pull to master.

**Comment by zzamboni** [comment]
@asmagill Thanks!

**Pull request merged**
