### PR TITLE
Add the window.fluent extension

### PR DESCRIPTION
**Pull request by knl**
window.fluent is a module for moving/resizing windows using a fluent interface,
which makes it really useful for creating succinct key-bindings.

### CODE REVIEW

**Comment by cmsj** [comment]
@knl apologies for the delay in getting to this review. We spoke about changing the name to something like hs.window.fluent, but I can't remember what we agreed on - do you?

**Comment by knl** [comment]
Hi @cmsj that is right :) However, I haven't had time to do the change. Let me do it today, and then have let's have a look.

**Comment by knl** [comment]
I've changed the name, please have a look.

**Comment by cmsj** [comment]
So, after some discussion in #hammerspoon with @lowne, as much as I like hs.window.fluent, I think it probably is better if we update hs.window's methods to return the window object, so they can be chained.
It's not as good as full, optimised fluency, but it does mean a simpler API. Perhaps we can also figure out a smart way to make the current API more chainable, without duplicating it.

**Pull request merged**
