### PR TITLE
support hs.alert at top/bottom edge of screen

### PR DESCRIPTION
**Pull request by freewizard**
support `hs.alert.show` at top/bottom edge of screen with `atScreenEdge` in style parameter
```
  hs.alert.show("HUD Alert Example", {
    strokeWidth  = 2,
    strokeColor = { white = 0, alpha = 1 },
    fillColor   = { white = 0, alpha = 0.8 },
    textColor = { white = 1, alpha = 1 },
    textFont  = ".AppleSystemUIFont",
    textSize  = 16,
    radius = 8,
    atScreenEdge = 1, -- 1 for top, 2 for bottom
  })
```

### CODE REVIEW

**Comment by latenitefilms** [comment]
Great idea!

**Comment by freewizard** [comment]
@latenitefilms thank you. Another thing I'm working on local branch is to add support of [translucency](https://developer.apple.com/documentation/appkit/nsvisualeffectview) to hs.drawing which should make hs.alert even sexier.

**Comment by asmagill** [comment]
@freewizard, You may want to consider adding translucency to `hs.canvas` instead/as well... it's a lot more powerful than the drawing module and there has been some thought about removing drawing completely at some point in favor of canvas -- there is even a module wrapper that allows existing code which uses `hs.drawing` to still function (see [hs.canvas.drawing](http://www.hammerspoon.org/docs/hs.canvas.drawing.html)) to preserve backwards compatibility.

**Comment by freewizard** [comment]
@asmagill thank you for sharing that, saved me from wrong direction.

**Comment by asmagill** [comment]
@freewizard if I'm reading the code correctly, specifying a screen edge of top or bottom places the alert *AT* the top or bottom, no adjusting for existing alerts which might still be hanging around because they haven't faded yet -- it's only the center ones that try not to overlap, correct?

I'll try it out myself later, but I wanted to first see if I understand correctly, and if this understanding *is* correct, I would ask that you add something in the docs to make this more clear and then I'll be happy to merge it.

**Comment by freewizard** [comment]
added. thanks, @asmagill

**Comment by R0dri** [comment]
hello, this edition is great. Any way in adding support for showing alerts at screen corners? (i.e. screen top; left)

**Pull request merged**
