### PR TITLE
Add custom window title comparison to hs.layout.apply().

### PR DESCRIPTION
**Pull request by wsmith323**

### CODE REVIEW

**Comment by cmsj** [comment]
Thanks for re-visiting this. How about we go all out and make that optional argument be called something like `windowTitleComparator` and have it accept a function. Said function should accept two string arguments and return true if they match, false if not.

If the argument is omitted we supply our own function that just uses ==, otherwise we use the function the user supplied. This would let people supply `string.match` or any other thing of their choice.
(and we should suggest using `string.match` as an example)

**Comment by wsmith323** [comment]
That is a great idea. I'll implement it.

**Comment by wsmith323** [comment]
Done.

**Comment by wsmith323** [comment]
Done.

**Comment by wsmith323** [comment]
Done.

**Comment by cmsj** [comment]
Thanks!

**Pull request closed without merging**
