### PR TITLE
[Review] Update hs.screen:name for M1 macs

### PR DESCRIPTION
**Pull request by asmagill**
Uses NSScreen's localizedName attribute introduced in 10.15

Addresses #2663 

Apparently M1 macs no longer use IOKit for maintaining display information which means IODisplay* no longer provides useful information on these machines. This change to the macOS will likely also result in `hs.screen:get/setBrightness` and `hs.brightness` to be useless... At present I am not aware of any promising leads for a work-around.

### CODE REVIEW

**Comment by asmagill** [comment]
Tested against M1 MacBook Pro running 11.2 and iMac running 10.15 (which should use new method as well as it's 10.15 -- but I can confirm on my machine the names match the ones returned by the previous code). A test against 10.14 would be appreciated, if anyone running development builds still uses it.

**Comment by cmsj** [comment]
Great find! I suspect we may have to just mark the brightness calls as unavailable on M1 macs, and hope that Apple gives us some API in the future.

**Comment by latenitefilms** [comment]
Tested on macOS 10.14.6:

```lua
> for _, screen in pairs(hs.screen.allScreens()) do
	hs.printf("name: %s", screen:name())
end
2021-02-10 17:57:24: -- Loading extension: screen
2021-02-10 17:57:24: name: LG UltraFine
2021-02-10 17:57:24: name: Color LCD
```

**Comment by cmsj** [comment]
@asmagill FYI, CI should be fully fixed now, so if you want to get results, rebase your PRs onto `master` and re-push them 👍

**Pull request merged**
