### PR TITLE
Update CREDITS.md

### PR DESCRIPTION
**Pull request by jhgg**
Hey,

I was the original author of the audiodevice, battery and brightness modules used in Hammerspoon today.

https://github.com/jhgg/hydra/blame/master/Hydra/API/battery.m
https://github.com/jhgg/hydra/blob/master/Hydra/API/brightness.m
https://github.com/jhgg/hydra/blob/master/Hydra/API/audiodevice.m

Would be awesome to be credited, thanks :)

### CODE REVIEW

**Comment by cmsj** [comment]
@jhgg Thanks! Very sorry we missed that from git history surveying. I'll add you to the LICENSE files for each of those extensions too.

**Comment by cmsj** [comment]
(see also a6de5c1 )

**Comment by jhgg** [comment]
Thanks @cmsj! You know, I'm still using Hydra 1.x, still need to have some time to update my config and stuff to HS.

**Comment by asmagill** [comment]
I'll also apologize ... a good bit of the porting from Hydra to Mjolnir and then Hammerspoon of your modules was done by me, and while I remember mentioning you in the readme.md files that accompanied the luarocks and git repos for Mjolnir modules, I'm not sure that I was quite as consistent in the source code itself, which I think is what most of the review was based off of since that's what's in the Hammerspoon extensions folder.

**Comment by cmsj** [comment]
@jhgg we'd love to have using HS :D

**Comment by jhgg** [comment]
It's all good @asmagill, stuff happens when you're iterating on an awesome product quickly.

**Comment by mgee** [comment]
While you're at it, I wrote `hs.application.watcher` :-)

**Comment by cmsj** [comment]
@mgee argh! Sorry. We'll clear that up shortly.

**Pull request merged**
