### PR TITLE
Issue #1876 - Updated refreshChoicesCallback() to take into account current query string

### LINKED ISSUE #1876: hs.chooser:refreshChoicesCallback() doesn't take into account query string?
When you trigger `hs.chooser:refreshChoicesCallback()` it doesn't seem to take into account the current query string?

For example, if you have the following choices:

```
a1
a2
a3
b1
b2
b3
```

...and your query string is "a", you'll only see the choices starting with "a".

However, if you trigger `:refreshChoicesCallback()` via a contextual menu, it reloads all the choices, but doesn't take into account the existing query string value, so "b1", "b2" and "b3" are now visible, even though the query string still says "a".

Here's some test code:

```lua
test = hs.chooser.new(function(result)
	print(string.format("Result: %s", hs.inspect(result)))
end)

local function getChoices()
	return {
		{ ["text"] = "a1" },
		{ ["text"] = "a2" }, 
		{ ["text"] = "a3" }, 
		{ ["text"] = "b1" }, 
		{ ["text"] = "b2" }, 
		{ ["text"] = "b3" }, 				
	}
end

test:choices(getChoices)

test:rightClickCallback(function()
	test:refreshChoicesCallback()
end)

test:show()
```

I've tried capturing the `:query()` then re-applying it after `:refreshChoicesCallback()`, but that has no impact.

Any ideas @cmsj or @asmagill ?

### PR DESCRIPTION
**Pull request by latenitefilms**
- Updated `hs.chooser:refreshChoicesCallback()` to take into account
the current query string
- Closes #1876

### CODE REVIEW

**Comment by latenitefilms** [comment]
@cmsj - Can you please test this to see if it solves #1876 without breaking cursor selection?

**Comment by latenitefilms** [comment]
Here's some basic test code for anyone who wants to test these changes:

```lua
local chooser = require("hs.chooser")
local console = require("hs.console")
local inspect = require("hs.inspect")
local styledtext = require("hs.styledtext")

local completionFn = function(result)
	print(string.format("Result: %s", result and inspect(result)))
end

local fancyText = styledtext.new("First Choice", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 18 },
    })

local fancySubText = styledtext.new("This is the subtext of the first choice", {
        color = {hex = "#FF0000", alpha = 1},
        font = { name = "Futura", size = 12 },
    })

console.printStyledtext(fancyText)
console.printStyledtext(fancySubText)

local function getChoices()
    return {
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },
        {
            ["text"] = fancyText,
            ["subText"] = fancySubText,
            ["uuid"] = "0001"
        },
        { 
            ["text"] = fancyText,
            ["uuid"] = "Bbbb"
        },
        { 
            ["text"] = "Third Possibility",
            ["subText"] = "What a lot of choosing there is going on here!",
            ["uuid"] = "III3"
        },				
    }
end

theChooser = chooser.new(completionFn)
	:choices(getChoices)
	:rightClickCallback(function() 
	    theChooser:refreshChoicesCallback() 
	    print("refresh!")
	end)
	:show()
```

**Comment by cmsj** [comment]
Sorry, I had to revert this because cursor selection is still broken. My bad for messing up testing it :/

**Comment by latenitefilms** [comment]
Huh, that’s weird. I’ve already merged this into CommandPost and I’m pretty sure it’s working? I’m overseas at the moment but will review again as soon as I can.

**Comment by latenitefilms** [comment]
Moved to new pull request here: #1974

**Pull request merged**
