### PR TITLE
[READY] add hs.logger history stuff

### PR DESCRIPTION
**Pull request by lowne**

### CODE REVIEW

**Comment by asmagill** [comment]
I've been thinking about this while working on adding logging methods to LuaSkin... would there be objections to my creating a "global" logging instance (maybe with the tag "LuaSkin" or "hammerspoon" that could capture items we log through these methods wth LuaSkin? Using this from the C-side isn't that difficult -- I've done it with hs.speech, if anyone wants to review the steps.  I'd make it part of the delegate, so the actual integration with this module would probably be in MJLua.m, rather than LuaSkin, but thats an implementation detail.

**Comment by lowne** [comment]
No objections, other than to id it 'HS-core' (LuaSkin is meaningless to users, and hammerspoon too generic (and long)); I should also point out (just in case) that if the proposed implementation uses shortcuts to "require" and use `hs.logger` before the user's `init.lua` is loaded (in MJLua or _coresetup), any logging there will be lost because I'm defaulting the history to disabled; so if that's desirable for some reason, either history must be enabled by default, or some other workaround is necessary.
Lastly, after quickly looking at `hs.speech`, I don't understand why you're using the 'f' method variants since it seems that all string formatting is done in-situ via `stringWithFormat` (which is appropriate).

**Comment by asmagill** [comment]
Unless you've changed something recently, when I last looked at the source for the module (admittedly a while back), the non-f versions were wrappers that called the f versions... thus calling them directly is one less function call in the path.

**Comment by lowne** [comment]
Correct, but they expect a format argument: `log.i(s)=>log.f('%s',s)` - which I can't find in `hs.speech` (I'm probably just misreading line 38). Speaking of performance, Lua's overhead seems to be minimal anyway: if I call `logger.printHistory(...)` right after a config reload, it takes north of 3 seconds, if I store the string on another table and take out the `print`, it takes 0.05s - afaict the bottleneck must be in OjbC's logmessage.

**Comment by asmagill** [comment]
(moving the conversation from #699 back to where it belongs)

Your argument re the '%' in the text is a good one... I'll switch things over (I think at atm the only core module affected is hs.speech, though I'll probably switch it to the LS method, once its in place)

As a side note, it is a little confusing having both, especially as I see it (rightly or wrongly) as an analog to print, and lua doesn't have a printf, you're expected to use print(string.format(...))... I go back and forth as to whether I consider that a "Good Thing"™, so not a comment/suggestion as much as an observation.

I'll review the docs more closely later and perhaps make some suggestions to make the distinctions more clear, if they're not in the present incarnation -- I admit, its been a while since I've looked closely at hs.logger's details.

And if I came across as defensive, consider it lack of sleep, too many holiday visitors, etc... I didn't take it badly, I just thought I was being clever removing an (as I saw it) unnecessary step.  But I had completely forgotten about a raw % in the text.

**Comment by asmagill** [comment]
(incidentally, the C-API does have a `lua_pushfstring`, so it is curious that it doesn't have a `printf`)

**Comment by lowne** [comment]
I find `print(string.format(...))` (and having to liberally sprinkle `string.format`s around in general) quite annoying, so despite my Lua-purity advocacy I wouldn't object to exposing a global `printf`; similarly, I exposed the 'f' variants in logger. (Typing aversion for frequently used stuff is also the reason the methods are called `d`/`df` etc., instead of `debug`/`debugf`)
The docs are admittedly a bit sparse (to be charitable) so improvements are welcome.

**Comment by cmsj** [comment]
+1 a global printf(), I hate doing string.format or "foo"..bar

**Comment by lowne** [comment]
Question: should the log history survive reloads (which requires persisting it)?

**Comment by asmagill** [comment]
You can use something like

~~~lua
local tmp = hs.crash.crashLogToNSLog()
hs.crashLogToNSLog(true)
hs.crash.crashLog("whatever")
hs.crashLogToNSLog(tmp)
~~~

to put things into the system logs available via the Console application, so I don't see this as a "must have" option... we'd either need to add aging or a size limit to keep it from getting too large anyway, so unless someone has a strong opinion, I wouldn't bother.

**Comment by lowne** [comment]
The history table is already size-limited to whatever is passed to `logger.historySize()`, with a hard ceiling of 10k entries (which might need increasing), so we could just dump/retrieve the table as is.

**Comment by asmagill** [comment]
A thought re `printf`: might it be more appropriate to make it `hs.printf`?  Making it printf "pollutes" the lua global namespace, which we're generally trying to avoid.  It also makes it obvious that the command isn't part of Lua, but rather a Hammerspoon specific addition.

It's simple enough in a module or even a users `init.lua` to add `printf = hs.printf` for simplicity when typing (tbh, I probably will, if the name change occurs, much like I do with `hs.inspect`).  

No strong feelings one way or the other, but did feel I should point out that it is a divergence from our normal practice.

**Comment by cmsj** [comment]
I think hs.printf is probably best, with a Notes suggestion to alias it into the global namespace

**Comment by cmsj** [comment]
Looks like Travis failed transiently - it was in the setFrame() UI test. Perhaps they are not as reliable as I hoped :(

In theory, closing the PR and re-opening it should trigger a rebuild.

**Comment by lowne** [comment]
@asmagill yep
@TravisPlusTheTestWriter(s) very regression such awesome 10/10 would test again
Although watching the build log go, I'm always reminded of [this](http://downlode.org/Etext/nine_billion_names_of_god.html), which I read decades ago - skimming through it right now I immediately found an apt quote to justify my feeling, as it describes the experience with utter accuracy:
> For weeks now the Mark V had been churning out acres of sheets covered with gibberish

(I'm merely following in asmagill's footsteps with the scifi references, so blame him 😀)

**Pull request merged**
