### PR TITLE
Save Console Location - Issue #1338

### LINKED ISSUE #1338: Console doesn't remember its last location
Currently the Console doesn't automatically remember it's last location, even though `Restorable` is enabled in `ConsoleWindow.xib`.

### PR DESCRIPTION
**Pull request by latenitefilms**
* Save & Restore the last Console Window location using Defaults (rather than always centre)
* Closes #1338

### CODE REVIEW

**Comment by cmsj** [comment]
This one also seems to have your full CommandPost fork changes, which makes for quite an unwieldy diff ;)

**Comment by cmsj** [comment]
I think https://github.com/Hammerspoon/hammerspoon/pull/1339/commits/95f99a9959d478400a146c43726cd44fe140b71d is the actual commit you want to propose?

**Comment by latenitefilms** [comment]
Yikes! Sorry about that!!

I think the problem is, initially I'm just working in a straight Hammerspoon fork, which works fine when I do a pull request from my Hammerspoon fork to the main Hammerspoon repository - but after I do that I also do a pull request from my Hammerspoon fork to the CommandPost-App repository, which seems to also affect the original pull request. Apologies! Need to work out why it does this and how to stop doing that in future!

Yes, that commit is the one - but only the bottom file.

**Comment by cmsj** [comment]
It's worth noting that GitHub PRs are not fixed in time, they track the branch you've asked to be merged, so if you push more stuff onto that branch, it will show up in the PR.

My suggestion would be to do each bugfix/feature on its own local branch, and when it's ready, you have a branch which only has the differences you want in a PR. If you started that local branch based off Hammerspoon's master, you're immediately fine to push your fix/feature branch to GH and open a PR. If that local branch was based off CommandPost's master, you'd make a new local branch off Hammerspoon's master and cherry-pick the commit(s), and then push/PR.

Simple ;)

**Comment by latenitefilms** [comment]
That's the strange thing, that what I THOUGHT I was doing, as the branch I've pushed doesn't contain any CommandPost code: 

https://github.com/latenitefilms/hammerspoon/commits/issue-1338-save-console-location

Obviously I'm doing something wrong when I also try and bring this branch into the CommandPost-App branch.

**Comment by latenitefilms** [comment]
Actually, no that branch does has all the CommandPost changes, so I have no idea what's going on. Apologies! Will try and prevent this from happening in future!

**Pull request closed without merging**
