### PR TITLE
Convert almost all uses of lua_pcall to LuaSkin's protectedCallAndTraceback

### PR DESCRIPTION
**Pull request by cmsj**
Reasonable reduction in code, dramatic reduction in complexity/fragility (IMO). Relates to #477 in some ways.

I'm testing this branch now, and I'll land it in the next day or so unless I hear any objections or find any issues (or discover there is no usable Internet at the place I'm travelling to tomorrow :)

### CODE REVIEW

**Comment by asmagill** [comment]
Lots o changes! I'll merge the pull locally as well and let you know if I find anything.

**Comment by cmsj** [comment]
@asmagill pushed another commit that also removes the lua_State pointers from the various userdata structs.

Note that I skipped hs.keycodes because I'm not touching that module any more than I have to, until it's had an ARC conversion (our last outstanding one). I also skipped hs.notify because the relevant section of its code, terrifies me ;)

**Comment by asmagill** [comment]
I'll take a look at the two... yeah, I've progressed a bit since notify and it probably could stand an overhaul.

**Comment by asmagill** [comment]
WRT to keycodes, looking at its history in the log file, I'm not entirely certain I see the hesitation with bringing it into line with ARC... As I understand it we basically want to use __bridge_retained when storing a retainable type in the userdata (the observer in this case) and then __bridge_transfer during __gc (and maybe stop, case depending) when removing it from the userdata... all other times use __bridge.  That's simplified a bit, but that's the gist of what I understand we need to be doing...

Did this cause crashes before?  Or compile errors?  I'll give it a shot later tonight, but if there was specific behavior to look for, it would help in testing.

**Comment by asmagill** [comment]
Ok, I don't know what to do within Xcode to ensure this compiles with ARC enabled, but if you want to take a look at my initial take on keycodes, it's at: https://github.com/asmagill/hammerspoon/tree/480plus

I don't normally change layouts, but I added a few, added a watcher function, switched between them, and reloaded/restarted a few times all making sure that it was loading from my locally installed copy (sometimes the CLS barfing of every require to the log comes in handy  😜)... what else should be checked?  (Oh, and take a look at the changes I made to use your protect skin method and skin lua_state... correct? -- it worked, but it's always good to have a second opinion.)

**Comment by cmsj** [comment]
@asmagil lgtm. To enable ARC in Xcode, go to the Hammerspoon project at the very top of the project explorer (cmd 1), in the right pane scroll to the keycodes target, in its build phases tab open the Compile Sources section and remove -fno-objc-arc from the compiler options column. Simple ;)

(Fortunately we don't use that per-file compiler options thing for any other files)

**Comment by cmsj** [comment]
@asmagill Thanks for doing keycodes, I cherry-picked it onto the branch.

How do you feel about landing this? I think I'm ready :)

(as for notify, I hope I didn't come across as rude, I very much appreciate the work you did on it, but I think we do need to rewrite it. There is something very wrong with the lifecycle of the various objects, and I had to do terribly hacky things to keep it from crashing all the time)

**Comment by asmagill** [comment]
Agreed, and I understand --  it was my first real attempt at doing something in Objective-C for OS X that wasn't just porting and tweaking or minor additions, and it shows.

I agree it needs an overhaul, and I even have some thoughts on moving some of the logic back into lua and *maybe* even making it handle responding to notifications whose clickbacks trigger the relaunching of Hammerspoon... but that is a little further off, as it will also require (hopefully minor) changes to the core app and I tread lightly there.

Like you, I'm a little hesitant to touch it and almost want to redo it from scratch.

It's on my radar, though, and I plan to tackle it this weekend.

As for the rest of pull 480's changes, go for it. I've been using it for a couple of days now and haven't seen any problems that I didn't create myself!

**Pull request merged**
