### PR TITLE
[READY] Fixed various bugs in hs.uielement

### LINKED ISSUE #1104: hs.application.watcher error using hs.uielement
I set up a hotkey to grab the current text selection like this:

```
local text = hs.uielement.focusedElement():selectedText()
```

It seems to be firing this error every time I switch application context. Doesn't seem to affect what I'm doing, but it fills up the log:

```
LuaSkin: hs.application.watcher callback error: ....app/Contents/Resources/extensions/hs/uielement/init.lua:72: attempt to index a userdata value (local 'app')
```

Build: 0.9.50
OSX Version: 10.12.1

### PR DESCRIPTION
**Pull request by latenitefilms**
- Closes #1104

### CODE REVIEW

**Comment by latenitefilms** [comment]
@cmsj & @asmagill - You might want to review the discussion [here](https://github.com/Hammerspoon/hammerspoon/issues/1793#issuecomment-389339927) before merging this, as there may still be some other work that needs to be done.

**Comment by asmagill** [comment]
The changes look good as far as catching and preventing lua errors when assumed parameters aren't present (or are `nil`). Do we know if, for the specific cases where errors were being thrown, if the parameter was *supposed* to be `nil` or does it being `nil` suggest a lower level problem?

**Comment by latenitefilms** [comment]
I've never really had much luck with `hs.uielement` in general to be honest, so I haven't look into it too deeply.

**Comment by latenitefilms** [comment]
FWIW: Unless @asmagill or @cmsj has time to review `hs.uielement` in more depth (which I'm guessing neither of you probably do?), I'd suggest we just merge this, as the original issue (#1104) said they were just having log spam, rather than something not working.

**Pull request merged**
