### PR TITLE
[READY] Fixed a regression in hs.eventtap.event:post([app])

### LINKED ISSUE #2498: 0.9.80 broke hs.eventtap.event:post()?
I have some code that basically does the following (the snippet in questions send a `;` keypress to the `YT Music` application which plays/pauses playback). Since upgrading to 0.9.80 it does not seem to work any more. The simplified example that follows does not either - no error thrown, it just doesn't seem to do anything. I've tried sending other keystrokes and to other applications with no apparent success.

```
> yt = hs.application.find("YT Music")
> e = hs.eventtap.event.newKeyEvent(";", true)
> e:post(yt)
hs.eventtap.event: Event type: 10 (0x6000019bc938)
```

### PR DESCRIPTION
**Pull request by latenitefilms**
- Closes #2498

### CODE REVIEW

**Comment by asmagill** [comment]
So you didn't need to make any additional linkings in the subproject? That's good to know. I'll test this out later tonight and, barring any surprises, land it.

**Comment by latenitefilms** [comment]
Nope, this works as-is. If I get a chance today, I'll try have a look around the other extensions and see if there's any other `hs.window`/`hs.application` stuff that's broken.

**Comment by latenitefilms** [comment]
FWIW - I've done a search for `AXUIElementRef`, and I don't spot any other obvious problems. It's only really used in `HSuicore`, `hs.application`, `hs.axuielement`, `hs.uielement` and `hs.window`.

**Comment by asmagill** [comment]
In `hs.webview` and `hs.console`, there is a method, `:hswindow()` but in both cases the relevant code is:

~~~objc
    CGWindowID windowID = (CGWindowID)[theWindow windowNumber];

    [skin requireModule:"hs.window"] ;
    lua_getfield(L, -1, "windowForID") ;
    lua_pushinteger(L, windowID) ;
    lua_call(L, 1, 1) ;
~~~

This is safe because it's leveraging `hs.window.windowForID` which means all of the relevant heavy lifting is already in `hs.window` and not in assumptions in `hs.webview` or `hs.console`.

While I still want to remove the code for these, since it's written in a way that won't cause problems, we can safely put that off for a while.

**Comment by asmagill** [comment]
verified

**Comment by asmagill** [comment]
Oh, @cmsj, my request re holding up 81 here has passed, though I do hope we can fix #2465 first.

**Pull request merged**
