### PR TITLE
Add modifier keycodes to hs.keycodes.map

### PR DESCRIPTION
**Pull request by knu**
Does it make sense to add these?

### CODE REVIEW

**Comment by knu** [comment]
A typical use case for these codes is to check which key is actually pressed for a flagsChanged event and only react to the right or left shift key.

**Comment by asmagill** [comment]
My thoughts:

* For consistency with the way we name things, `rcmd`, `rshift`, `ralt`, and `rctrl` should be camel cased.  Further, my preference would be to spell out right (e.g. `rightCmd` instead of `rCmd`, etc.)
* The docs either within `hs.keycodes.map` or `hs.hotkey.bind` should make it clear that these specific keymappings cannot be used in hotkey binding -- they are strictly for use with `hs.eventtap`

Since a future update I am working on for `hs.eventtap` was going to introduce these anyways, I have no objection to adding them now.

**Comment by knu** [comment]
@asmagill OK, thanks for sharing your thoughts and a future plan.  I just named them after the existing mnemonics such as "forwarddelete", "pageup" and "padenter" which don't use upper case letters.  Perhaps we should make them all camel cased and make lookup case-insensitive by using a metatable, so common mistakes to spell one letter key in upper case would be covered.  What do you think?

**Comment by cmsj** [comment]
@knu I like the sound of that :)

**Comment by asmagill** [comment]
forgot that hs.keycodes.map is one of the few places we haven't properly camel-cased yet... sounds like a good compromise, so 👍

**Comment by knu** [comment]
Oh wait, there's reverse lookup also.  Returning the camel-cased name  for a keycode might break user code.  While case-insensitivity may be great, should we keep compatibility and have lower-case names in the map for now?

**Comment by cmsj** [comment]
@knl you make a good point, let's not break things. Sorry for the mixed signals on this!

**Comment by knl** [comment]
@cmsj I think you meant @knu :)

**Comment by cmsj** [comment]
@knl sorry :)

**Comment by asmagill** [comment]
Ok... then I think the question becomes `ralt` or `rightalt`... I favor the later, but either is fine.

I may consider amending the metafunctions later to allow referencing them by name in a camelCased fashion because I think it looks and reads better, but I agree that the reverse should stay the same lowercased version for backwards compatibility.

**Comment by knu** [comment]
@asmagill My bad, the forward lookup (name -> keycode) was already made case-insensitive.
https://github.com/Hammerspoon/hammerspoon/blob/67eb825ee6753f6a77b13b0017a48d6f886f3e35/extensions/keycodes/init.lua#L49-L52

So I just changed the `r`- names to `right`- to suit your tastes.

**Comment by knu** [comment]
I thought for a moment of making the new keys camel-cased like `rightCmd`, but that would introduce inconsistency users would hardly welcome, so why not just leave the consistency argument for now and revisit until the keycodes/hotkey framework gets a revamp?

**Comment by cmsj** [comment]
@knu it looks like, at the moment, some of the key names in the docstring comment, don't match the names that are going in the table? (e.g. "rcmd" vs "rightcommand")

**Comment by knu** [comment]
@cmsj Thanks, fixed!

**Comment by cmsj** [comment]
Thanks :)

**Pull request merged**
