### PR TITLE
add hs.image:encodeAsURLString

### PR DESCRIPTION
**Pull request by asmagill**
Can convert image into string (and back with `hs.image.imageFromURL`)

### CODE REVIEW

**Comment by asmagill** [comment]
objections?

**Comment by asmagill** [comment]
Added code so that resizing an un-composited (i.e. not displayed on the screen) image will carry the resize into `saveToFile`, `croppedImage`, and `encodeAsURLString`

**Comment by asmagill** [comment]
Ok, *now* I'm ready to land this if there are no objections

**Comment by cmsj** [comment]
@asmagill lgtm

**Pull request merged**
