### PR TITLE
Add method to hs.image to create bitmap representation of image for external devices

### PR DESCRIPTION
**Pull request by asmagill**
Addresses #2807

### CODE REVIEW

**Comment by asmagill** [comment]
@cmsj, skimmed the Contributions document and as usual, I'm behind on tests... what kind of tests would you think this method should have? I suppose I could create an image (maybe via ASCII or by system name) and then make sure that the bitmrep doesn't equal it, but *can* we do something more? What kind of tests would you do if you had added this? I'll write them, I'm just not quite sure what would be reasonable here...

**Comment by cmsj** [comment]
@asmagill even just checking that it returns an `hs.image` object would be a good first step. In the case of an image it's kinda hard to verify that the result is "correct" without looking at it, but maybe `hs.image:size()` would also make sense in a test that specifically constrains the size of the bitmap representation?

**Comment by latenitefilms** [comment]
@cmsj - Any chance we could merge this, and then I could do the tests in another pull request?

**Comment by cmsj** [comment]
Since this had a conflict with the new ascii method, I've merged this PR's branch by hand and pushed it as e9034e8a26442a406a1f21e99c594c4dc58293bf

**Pull request closed without merging**
