### PR TITLE
Updated to support Catalina Music.app

### PR DESCRIPTION
**Pull request by cuyler**
This a simple update that duplicates the iTunes extension with a Music extension. The app control functionality, via AppleScript works exactly the same.

I considered NOT using the generic 'Music' namespace, however that is technically what the app is called.

* For folks looking to just add music support: you can just grab this extension and manually add it to an existing install:

Go to: /Applications/Hammerspoon.app/Contents/Resources/extensions/hs
create a new folder/directory called "music" and drop this in and restart Hammerspoon.

You'll need to update iTunes references from 'hs.itunes' to 'hs.music' but it should otherwise work identically.

### CODE REVIEW

**Comment by cmsj** [comment]
Hmm, yeah, the generic `hs.music` is very unfortunate. I almost wonder if we should make `hs.itunes` detect which OS version it's on and change the name of the app it sends events to?

**Comment by cuyler** [comment]
That's a good take, honestly. I use HS for keyboard controlling my music so I was desperate for a quick fix. Let me take another look and I'll remove and resubmit this PR if I can make it reasonable.

**Comment by rsefer** [comment]
https://github.com/Hammerspoon/hammerspoon/blob/3fe9fb425505c76a1fb98e7a047b7f0983494862/extensions/itunes/init.lua#L26-L35

```lua
local applicationName = 'iTunes'
if hs.host.operatingSystemVersion().major >= 10 and hs.host.operatingSystemVersion().minor >=15 then
  applicationName = 'Music'
end
if local _cmd = 'tell application "' .. applicationName .. '" to ' .. cmd
```

**Comment by cmsj** [comment]
I'm going to close this because I just merged a PR that detects the macOS version and uses `iTunes` or `Music` appropriately. Thanks very much though!

**Pull request closed without merging**
