### PR TITLE
Don't assume that we can always make a UTF8 string out of the HTTP re…

### PR DESCRIPTION
**Pull request by cmsj**
…sponse body. Determine behaviour from the Content-Type response header

Ping @asmagill for sanity check :)

(this is in response to an issue raised on IRC by @zzamboni)

### CODE REVIEW

**Comment by asmagill** [comment]
FYI, LuaSkin's pushNSObject does handle NSData objects, so I might have made `responseBodyToLua` return a type of `id` and made the object returned NSString, if text, or NSData if not.

However, coding choices aside, looks good to me.

**Comment by zzamboni** [comment]
The patch seems to work fine for both `get()` and `asyncGet()`.

**Comment by cmsj** [comment]
@asmagill doh, that's a very good point! I'll update the PR :)

**Comment by cmsj** [comment]
@zzamboni would very much appreciate if you could test the updated PR here. It should work exactly as the previous version, just less code and more @asmagill awesomeness \o/

**Comment by zzamboni** [comment]
@cmsj the updated patch also seems to work OK!

**Pull request merged**
