### PR TITLE
Add module for mouth noise detection

### PR DESCRIPTION
**Pull request by trishume**
This is the distilling of my [thume.popclick](https://github.com/trishume/thume.popclick) module into a built-in extension. It contains high-accuracy low-latency audio recognizers for mouth noises suitable for miscellaneous simple computer control tasks. I personally use this module with eventtap to scroll documents hands free when I am lying down with my laptop reading. In the past I've used these recognizers in research for hands-free mouse clicking.

I apologize for the C++, but it's what I originally wrote the recognizers in, and the high speed collections make it nicer than Objective-C or C.

Because of the way the audio system I use works I had to have an unusual structure of an objective-C class containing an instance variable struct that the audio system takes direct pointers into.

It's decidedly hard to test automatically since it relies on microphone input, but I included a basic doesn't-crash automated test. I'm not sure if it crashes on Travis but if it does I'll add the skip travis call. But rest assured I've been testing this personally for the past week and it has worked fairly well.

See the docs in init.lua for more info, or the readme of the project I link above.

@cmsj @asmagill

### CODE REVIEW

**Comment by trishume** [comment]
Also, I couldn't run the tests myself because if I use Product->Test in XCode it crashes because it tries to look for `Hammerspoon Tests.xctest` in the `Plugins` folder of `Hammerspoon.app` but it isn't there.

**Comment by asmagill** [comment]
Interesting idea, I look forward to checking it out this weekend!

**Comment by trishume** [comment]
The `-Wall -Werror` flags on Hammerspoon are *brutal*. I thought it would take an hour to port my module to Hammerspoon, I've now spent like 4 hours refactoring and fixing to avoid warnings. Including the most recent one which Travis has but my compiler doesn't.

When ready I can squash some/all of these commits together before merging if you'd like.

**Comment by trishume** [comment]
Ping @asmagill @cmsj

**Comment by asmagill** [comment]
LGTM

**Comment by cmsj** [comment]
@trishume sorry for the delay, and sorry that you had to feel the pain of -Wall -Werror. I think it's worth it, to keep our quality levels from slipping further! Thanks very much for writing this module, it's crazycool :)

I can imagine other uses for an FFT engine, in companion with things like a PushToTalk microphone muter that reminds you you're muted if you're speaking, but I know nothing about FFTs and have no idea how to do such things!

**Pull request merged**
