### PR TITLE
Add hs.screen:getInfo()

### PR DESCRIPTION
**Pull request by cmsj**

### CODE REVIEW

**Comment by FloWi** [comment]
I figured out how to create an executable and tried your branch, @cmsj.

```lua
hs.hotkey.bind({"cmd", "alt", "ctrl"}, "I", function()
  for key, screen in pairs(hs.screen.allScreens()) do
    print("===================")
    print("name: " .. screen:name())
    print("id: " .. screen:id())
    print("uuid: " .. screen:getUUID())
    if (screen:getSerial() == nil) then
      print("serial: not found (nil)")
    else
      print("serial: " .. screen:getSerial())
    end
  end
end)
```

Unfortunately the serial was `nil` for all displays :-/
That's a bummer.

```text
2022-03-20 17:59:11: ===================
2022-03-20 17:59:11: name: Built-in Retina Display
2022-03-20 17:59:11: id: 69734406
2022-03-20 17:59:11: uuid: 8B13405D-6BD3-944A-36D4-EB57C5D1B34D
2022-03-20 17:59:11: serial: not found (nil)
2022-03-20 17:59:11: ===================
2022-03-20 17:59:11: name: LEN LT3053pwA
2022-03-20 17:59:11: id: 731392265
2022-03-20 17:59:11: uuid: 8C023CC6-0D49-9DB5-1661-296511A6179B
2022-03-20 17:59:11: serial: not found (nil)
2022-03-20 17:59:11: ===================
2022-03-20 17:59:11: name: LEN LT3053pwA
2022-03-20 17:59:11: id: 731392266
2022-03-20 17:59:11: uuid: 38D985BB-1AD2-46D5-AF98-71D5B67DAD4C
2022-03-20 17:59:11: serial: not found (nil)
```

**Comment by FloWi** [comment]
LOLOLOL - I found you debug log. 

```text
2022-03-20 18:09:54.164057+0100 Hammerspoon[51147:2037524] LOLOLOL: {
    DisplayBacklight = 500;
    DisplayBluePointX = "0.1494141";
    DisplayBluePointY = "0.05175781";
    DisplayBrightReflection = 505;
    DisplayBundle = "CFBundle 0x61500007b000 </System/Library/Displays> (not loaded)";
    DisplayDarkReflection = "1.1";
    DisplayFixedPixelFormat = 1;
    DisplayGreenPointX = "0.2646484";
    DisplayGreenPointY = "0.6904297";
    DisplayHorizontalImageSize = 330;
    DisplayLeakage = "0.333";
    DisplayLowestLevel = 1;
    DisplayLowestMeasured = "0.4323";
    DisplayProductID = 41024;
    DisplayProductName =     {
        "en_US" = "Color LCD";
    };
    DisplayRedPointX = "0.6796875";
    DisplayRedPointY = "0.3203125";
    DisplaySubPixelLayout = 1;
    DisplayVendorID = 1552;
    DisplayVerticalImageSize = 210;
    DisplayViewAngleAffectsGamma = 1;
    DisplayWeekManufacture = 16;
    DisplayWhiteGamma = "2.2";
    DisplayWhitePointX = "0.3125";
    DisplayWhitePointY = "0.3291016";
    DisplayYearManufacture = 2017;
    IODisplayAttributes = {length = 40, bytes = 0x67617476 00000000 73676c66 04000000 ... 676c6664 00000000 };
    IODisplayConnectFlags = {length = 4, bytes = 0xc4490000};
    IODisplayEDID = {length = 256, bytes = 0x00ffffff ffffff00 061040a0 00000000 ... 00000000 0000be90 };
    IODisplayEDIDOriginal = {length = 256, bytes = 0x00ffffff ffffff00 061040a0 00000000 ... 00000000 0000be90 };
    IODisplayHasBacklight = 1;
    IODisplayIsDigital = 1;
    IODisplayIsHDMISink = 0;
    IODisplayLocation = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Palena@0/AMDFramebufferVIB/display0/AppleBacklightDisplay";
    IODisplayMobileBLTable = {length = 36, bytes = 0x00110000 02900365 04890618 08380b20 ... 625a8721 b9e3fd71 };
    IODisplayPrefsKey = "Alias:0/AppleBacklightDisplay-610-a040";
    IOFBTransform = 0;
    IOGFlags = 4;
    "display-resolution-preview-icon" = "/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-610/DisplayProductID-a030-9d9da0.tiff";
    "graphic-options" = 12;
    "resolution-preview-height" = 92;
    "resolution-preview-width" = 147;
    "resolution-preview-x" = 40;
    "resolution-preview-y" = 62;
    "scale-resolutions" =     (
        {length = 9, bytes = 0x00000f000000096000},
        {length = 9, bytes = 0x00000d200000083400},
        {length = 9, bytes = 0x00000b400000070800},
        {length = 9, bytes = 0x00000a000000064000},
        {length = 9, bytes = 0x000008000000050000},
        {length = 16, bytes = 0x00000a00000006400000000100200000},
        {length = 16, bytes = 0x00000a00000005a00000000100200000},
        {length = 16, bytes = 0x00000780000004b00000000100200000},
        {length = 16, bytes = 0x00000780000004380000000100200000},
        {length = 16, bytes = 0x00000500000002d00000000100200000},
        {length = 12, bytes = 0x000006720000041a00000001},
        {length = 12, bytes = 0x000005a00000038400000001},
        {length = 12, bytes = 0x000005000000032000000001},
        {length = 12, bytes = 0x00000480000002d000000001},
        {length = 12, bytes = 0x000004000000030000000001},
        {length = 12, bytes = 0x000003480000020d00000001},
        {length = 12, bytes = 0x000003200000025800000001},
        {length = 12, bytes = 0x00000280000001e000000001},
        {length = 16, bytes = 0x00000f00000009600000000900a00000},
        {length = 16, bytes = 0x00000d20000008340000000900a00000},
        {length = 16, bytes = 0x00000b40000007080000000900a00000},
        {length = 16, bytes = 0x00000a00000006400000000900a00000},
        {length = 16, bytes = 0x00000800000005000000000900a00000},
        {length = 16, bytes = 0x00000780000004b00000000900a00000},
        {length = 16, bytes = 0x00000780000004380000000900200000},
        {length = 16, bytes = 0x00000500000002d00000000900200000}
    );
    "target-default-ppmm" = "10.1510574";
}
2022-03-20 18:11:28.300028+0100 Hammerspoon[51147:2037524] LOLOLOL: {
    DisplayBluePointX = "0.1474609";
    DisplayBluePointY = "0.05371094";
    DisplayBrightnessAffectsGamma = 1;
    DisplayBundle = "CFBundle 0x61500007b000 </System/Library/Displays> (not loaded)";
    DisplayGreenPointX = "0.2099609";
    DisplayGreenPointY = "0.7001953";
    DisplayHorizontalImageSize = 640;
    DisplayProductID = 24740;
    DisplayProductName =     {
        "en_US" = "LEN LT3053pwA";
    };
    DisplayRedPointX = "0.6796875";
    DisplayRedPointY = "0.3095703";
    DisplayVendorID = 12462;
    DisplayVerticalImageSize = 400;
    DisplayWeekManufacture = 43;
    DisplayWhiteGamma = "2.2";
    DisplayWhitePointX = "0.3134766";
    DisplayWhitePointY = "0.3291016";
    DisplayYearManufacture = 2013;
    IODisplayAttributes = {length = 40, bytes = 0x67617476 00000000 73676c66 00000000 ... 676c6664 01000000 };
    IODisplayConnectFlags = {length = 4, bytes = 0xc4410000};
    IODisplayEDID = {length = 256, bytes = 0x00ffffff ffffff00 30aea460 01010101 ... 00000000 000000d8 };
    IODisplayEDIDOriginal = {length = 256, bytes = 0x00ffffff ffffff00 30aea460 01010101 ... 00000000 000000d8 };
    IODisplayIsDigital = 1;
    IODisplayIsHDMISink = 0;
    IODisplayLocation = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Palena@3/AMDFramebufferVIB/display0/AppleDisplay";
    IODisplayPrefsKey = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0-30ae-60a4-24baf3761480a4b6";
    IODisplayVSDB030C00 = {length = 3, bytes = 0x100010};
    IOFBTransform = 0;
    "display-icon" = "public.display";
    drng = {length = 18, bytes = 0x000000fd0032471e641e010a202020202020};
    "graphic-options" = 12;
    trng = {length = 312, bytes = 0x00000000 00000000 00000000 00000000 ... 00000000 00000000 };
}
2022-03-20 18:11:41.297368+0100 Hammerspoon[51147:2037524] LOLOLOL: {
    DisplayBluePointX = "0.1474609";
    DisplayBluePointY = "0.05371094";
    DisplayBrightnessAffectsGamma = 1;
    DisplayBundle = "CFBundle 0x61500007b000 </System/Library/Displays> (not loaded)";
    DisplayGreenPointX = "0.2099609";
    DisplayGreenPointY = "0.7001953";
    DisplayHorizontalImageSize = 640;
    DisplayProductID = 24740;
    DisplayProductName =     {
        "en_US" = "LEN LT3053pwA";
    };
    DisplayRedPointX = "0.6796875";
    DisplayRedPointY = "0.3095703";
    DisplayVendorID = 12462;
    DisplayVerticalImageSize = 400;
    DisplayWeekManufacture = 41;
    DisplayWhiteGamma = "2.2";
    DisplayWhitePointX = "0.3134766";
    DisplayWhitePointY = "0.3291016";
    DisplayYearManufacture = 2013;
    IODisplayAttributes = {length = 40, bytes = 0x67617476 00000000 73676c66 00000000 ... 676c6664 01000000 };
    IODisplayConnectFlags = {length = 4, bytes = 0xc4410000};
    IODisplayEDID = {length = 256, bytes = 0x00ffffff ffffff00 30aea460 01010101 ... 00000000 000000d8 };
    IODisplayEDIDOriginal = {length = 256, bytes = 0x00ffffff ffffff00 30aea460 01010101 ... 00000000 000000d8 };
    IODisplayIsDigital = 1;
    IODisplayIsHDMISink = 0;
    IODisplayLocation = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Palena@4/AMDFramebufferVIB/display0/AppleDisplay";
    IODisplayPrefsKey = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0-30ae-60a4-55bd00373315cc32";
    IODisplayVSDB030C00 = {length = 3, bytes = 0x100010};
    IOFBTransform = 0;
    "display-icon" = "public.display";
    drng = {length = 18, bytes = 0x000000fd0032471e641e010a202020202020};
    "graphic-options" = 12;
    trng = {length = 312, bytes = 0x00000000 00000000 00000000 00000000 ... 00000000 00000000 };
}
```

**Comment by FloWi** [comment]
I tried this but it returns `0` for all my screens :-/

```obj-c
    UInt32 serial = CGDisplaySerialNumber(screen_id);
    NSLog(@"CGDisplaySerialNumber: %u", serial);
```

```text
2022-03-20 18:16:40.595292+0100 Hammerspoon[51293:2045459] CGDisplaySerialNumber: 0

```

**Comment by cmsj** [comment]
@FloWi hah, I didn't actually mean to leave that debug logging in, but looking at your output, I wonder if exposing `IODisplayLocation` would be helpful. I have a suspicion that that would actually be stable and unique, because it should relate to the physical ports things are connected to.

**Comment by cmsj** [comment]
Perhaps also worth noting that yours differ on their week of manufacture. TBH we could just expose this entire dictionary and give users the maximum chance of finding *something* that provides a stable identifier between their displays?

**Comment by cmsj** [comment]
if you `git pull -f` your checkout of this PR, you should now have `:getInfo()` instead of `:getSerial()`

**Comment by FloWi** [comment]
I think it's a good idea to expose the whole dictionary. 
I didn't pay attention to the week number - could have stopped there already ;-)

I used your latest code and `IODisplayEDID` contains the serialnumber and reaches lua almost intact (`V1187020`)🎉 . 

```
2022-03-20 21:22:40: ------------
2022-03-20 21:22:40: IODisplayEDID
2022-03-20 21:22:40: string
2022-03-20 21:22:40: ∅������∅0��`+�@(x>��O5�%
PT�∅�∅���∅���∅�����∅�h∅��@.`0 6∅��!∅∅∅∅∅�∅V1188942
    ∅∅∅�∅2Gd
      ∅∅∅�∅LEN LT3053pwA�!�M�#	�∅∅f∅∅!�� @:`0@:∅��!∅∅�C∅�Q@:``�:∅��!∅∅f!P�Q∅0@p6∅��!∅∅�e��r@:`��:∅��!∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅∅�

2022-03-20 21:22:40: ------------
```

Just ignore the noise ;-)

This works already:
```lua
> string.find(hs.screen.allScreens()[2]:getInfo()["IODisplayEDID"], "V1188942")
78	85
```

We could also expose the edid information as a hex string from objective-c. Or maybe it's a case of yagni.

Annoying that you can't get the same representation of the decoded edid as `systemprofiler SPDisplaysDataType -json` does.

In the meantime I went down a rabbithole and tried to parse the [EDID specification](https://en.wikipedia.org/wiki/Extended_Display_Identification_Data#Structure,_version_1.4). 

Not easy at all. Especially for me as a bloody obj-c n00b.

I wrote down my findings below in case anyone wants to decode it.

Cheers.

According to the EDID specification, the serial number should be from bytes 12-15 of the EDID field.
These are all 0 case of my monitor.

My manufactorer put the serial number in the "Descriptor 2" field (bytes 72-89 - see screenshot)

image

```

I tried to get a string out of the edid-bytes, but I have no experience with objective-c and I don't think it's a good idea to fiddle with the low level bytes ;-)

```obj-c
        NSData *edidData;
        NSData *serialNumberData;
        
        edidData = [deviceInfo objectForKey:@kIODisplayEDIDKey];
        
        serialNumberData = [edidData subdataWithRange:NSMakeRange(72, 18)];
        
        NSLog(@"edidData %@", edidData);
        NSLog(@"serialNumberData %@", serialNumberData);
```

I found this gist, where someone decoded the EDID into a struct. Unfortunately I don't get this to work with objective-c. 
https://gist.github.com/william-reed/ac2d6306291da351a3332b87e20b596f#file-edid-reader-c

**Comment by latenitefilms** [comment]
This might also be a helpful reference:

https://github.com/timvideos/edid-decode/blob/master/edid-decode.c

**Comment by FloWi** [comment]
Of course the python community has a [package](https://pypi.org/project/pyedid/) for parsing edid :)

Does anyone know how to encode the `IODisplayEDID` as a hex-string in objective-c? We could expose that as a property to allow people to match on all kinds of properties. 

Here is an example. 

```bash
python edid_parse.py 00ffffffffffff0030aea460010101012b170104b54028783e1df5ae4f35b3250d5054a10800810081809500a9c0b300d1c081c0d100e26800a0a0402e603020360081912100001a000000ff0056313138383934320a20202020000000fd0032471e641e010a202020202020000000fc004c454e204c543330353370774101cf020321f14d90010203040607051112131f14230907078301000066030c001000107f2180e020403a6030403a0081912100001aad4300d051403a6060883a0081912100001c662150b051001b304070360081912100001edb6580c072403a6090d03a0081912100001c00000000000000000000000000000000000000000000d8 | jq
```

```python
import pyedid
import sys

edid_hex = sys.argv[1]
edid = pyedid.parse_edid(edid_hex)
json_str = str(edid)
print(json_str)
```

```json
{
  "manufacturer_id": 12462,
  "manufacturer": "Lenovo Group Limited",
  "product_id": 42080,
  "year": 2013,
  "week": 43,
  "edid_version": "1.4",
  "type": "digital",
  "width": 64,
  "height": 40,
...
  "resolutions": [
...
    [
      1920,
      1200,
      60
    ]
  ],
  "name": "LEN LT3053pwA",
  "serial": "V1188942"
}
```
Funny thing is that the resolution I'm using is not listed there - but hey 🤷‍♂️

**Comment by latenitefilms** [comment]
I think that [gist](https://gist.github.com/william-reed/ac2d6306291da351a3332b87e20b596f#file-edid-reader-c) you linked to earlier is probably the best plan of attack. Maybe there could be a new method like `:getEDID()` which reads the EDID information and returns a table of data?

In the meantime, you could play around with using `hs.utf8.hexDump` and passing that data along to your Python scripts:

http://www.hammerspoon.org/docs/hs.utf8.html#hexDump

**Comment by cmsj** [comment]
Just pushed a small change that preserves fields like `IODisplayEDID` which contain non-UTF8 values, rather than normalising them to UTF8.

**Comment by cmsj** [comment]
I had a quick play with that gist's code and it doesn't seem to cleanly adopt the raw bytes from the EDID info I'm getting for my monitor, and it would be quite a lot of careful work to properly expose it to Lua, so I think we might have gone far enough with this PR for now.

Any objections if I merge it as-is and we have at least a decent amount of extra information about displays?

**Comment by FloWi** [comment]
I'm completely fine with that. I think that whole EDID rabbit hole is way too deep for a small project and it seems lots of things can go wrong here. 

See Apple with all their resources not getting the serial number part right ;-) Even the python library is not feature complete. They have to maintain big dictionaries to translate bytes into meaning.
see [here](https://github.com/dd4e/pyedid/blob/master/pyedid/types/default.py#L6) and [here](https://github.com/dd4e/pyedid/blob/master/pyedid/types/edid.py#L91-L115)

Thanks for the tip with the hexdump, @latenitefilms. I'll play around with it if needed. 

Thanks for that feature and the interesting discussions! I learned a lot.

**Comment by cmsj** [comment]
thanks @FloWi for prompting an interesting avenue of discussion/investigation/improvement :)

**Comment by FloWi** [comment]
I stripped down the hexDump function to return a pure hex string and now it exactly matches the EDID from `ioreg` or `system_profiler`. 🎉 

```lua
function toHexString(stuff)
  local buffer = ""
  for c in string.gmatch(tostring(stuff), ".") do
    buffer = buffer..string.format("%02X",string.byte(c))
  end
  return buffer
end

toHexString(hs.screen.allScreens()[2]:getInfo()["IODisplayEDID"])
```

**Comment by FloWi** [comment]
Works like a charm now without an external program :)
Just sharing in case anyone else needs something like this.

```lua
mainMonitor = nil
rightMonitor = nil

function isMainMonitor(screen)
  local edid = screen:getInfo()["IODisplayEDID"]
  return string.find(edid, "V1187020") ~= nil
end

function isRightMonitor(screen)
  local edid = screen:getInfo()["IODisplayEDID"]
  return string.find(edid, "V1188942") ~= nil
end


function setupScreens()
  local all = hs.screen.allScreens()

  for _, screen in pairs(hs.screen.allScreens()) do
    if(isMainMonitor(screen)) then
      mainMonitor = screen
    elseif (isRightMonitor(screen)) then
      rightMonitor = screen
    end
  end

  if(mainMonitor == nil or rightMonitor == nil) then
    print("monitors not correctly identifed")
    return
  end

  print(" Main Screen: " .. mainMonitor:name() .. "; id: " .. mainMonitor:id() .. "; uuid: " .. mainMonitor:getUUID())
  print("Right Screen: " .. rightMonitor:name() .. "; id: " .. rightMonitor:id() .. "; uuid: " .. rightMonitor:getUUID())

  --[[
  correction: place "right monitor" at the top-right corner of "main monitor"
  the gap will be closed automagically by hammerspoon, or macOS

  =========================================================================
      wrong: macbook   |  right monitor  |   main monitor
        fix: macbook   |                 |   main monitor   |   right monitor
  after fix: macbook   |   main monitor  |  right monitor
  =========================================================================
  --]]

  if(mainMonitor:toEast() == rightMonitor) then -- all good :)
    print("monitors are correctly setup")
  else     
    print("monitors are recognized by macOS in the wrong order. Fixing their positions now")

    local m = mainMonitor:fullFrame()
    local r = rightMonitor:fullFrame()

    rightMonitor:setOrigin(m.x2, r.y)
  end
end
```

**Comment by cmsj** [comment]
Excellent work!

**Comment by FloWi** [comment]
Hi! 
I just got my new macbook with an M1 chip. I also upgraded to macOS 12.5.1 from 11.xx.x. I'm using the latest build of hammerspoon (0.0.97).

Unfortunately `screen:getInfo()` doesn't work anymore. I checked it for every screen in `hs.screen.allScreens()`. Does anyone know why this happens or how I can debug this?

**Pull request merged**
