### PR TITLE
[READY]: Issue #1561 - hs.dialog improvements

### LINKED ISSUE #1561: hs.dialog.textPromt keyboard focus
I really like the dialog.textPromt, but sadly the text input field doesn't have keyboard focus when it opens, and there doesn't seem to be anyway to get it without using the mouse. Is there some trick to do this?

If not it would be amazing if it could be implemented so it would open up with keyboard focus (possibly optional)

### PR DESCRIPTION
**Pull request by latenitefilms**
- CL: *Fixes*: hs.dialog.chooseFileOrFolder() now returns a full path
instead of NSURL
- CL: *Fixes*: hs.dialog.textPrompt() now focussed on text input on load
- Documentation Fixes
- Closes #1561

### CODE REVIEW

**Comment by latenitefilms** [comment]
As discussed in #1561, it would be good if we could also solve "tabbing" for `hs.dialog.textPrompt()` if you have any ideas @asmagill or @cmsj, otherwise this is good to go.

**Comment by latenitefilms** [comment]
@asmagill & @cmsj - This is now good to go.

Any questions let me know!

**Comment by latenitefilms** [comment]
@asmagill & @cmsj - If you're happy with these changes, any chance we could merge into the `master`?

**Comment by asmagill** [comment]
@cmsj, lgtm

**Pull request merged**
