### PR TITLE
[WIP] add image names from #752

### PR DESCRIPTION
**Pull request by asmagill**
I'd like to test these to make sure that they are current... no reason to include things we know aren't in the latest OS X, plus it gives me an excuse to play with hs.chooser  😁

And, should they all be in one list or broken out into the arrays like in this pull?

### CODE REVIEW

**Comment by cmsj** [comment]
I think it might be useful to have examples for iconForFileType - eg I don't know what an encoded hfs type is ;)

**Comment by asmagill** [comment]
The text is mostly copied from the docs... It thought it was the 4 character sequence used to identify file types when HFS was first introduced (and resource forks were used)... but in testing, it doesn't seem to work with the few I remember... a quick google shows people using `NSHFSTypeCodeFromFileType` to generate the code from a more traditional file type, so maybe it has to be encoded in a special way... 

I'd be just as happy removing the text from the doc strings unless you think it should be explored further.

**Comment by cmsj** [comment]
It sounds very legacy, so I think t can go. File extensions and UTIs seems plenty sufficient

**Comment by cmsj** [comment]
@asmagill OOI, what's still WIP on this?

**Comment by asmagill** [comment]
nothing, just forgot about it :-)  go ahead and land it or I will later today.

**Pull request merged**
