### PR TITLE
uielement and timer tweaks

### PR DESCRIPTION
**Pull request by asmagill**
* uielement now uses refTable like other modules instead of LUA_REGISTRYINDEX
* timer clears metatable on __gc and logs info that may help in debugging when it fails

I'm hoping these can help in tracking down some of the recurring crashes we're seeing that are related to timerCallback... or at least give a better picture of which timer so we can figure out where to focus...

@cmsj, please take a look and if you have no objections, I'd like to get this in master so those that use developer builds can start chiming in... 

And if you can think of more checks to add or stuff to log, please let me know... this is vexing me in its inconsistency!

EDIT: also modified toNSObjectAtIndex: so that it returns nil rather than [NSNull null], if the function has not yet recursed, per #880.

### CODE REVIEW

**Comment by asmagill** [comment]
switched to logBreadcrumb so hopefully we get some info even during a crash

**Comment by heptal** [comment]
Though not merged, I do have some tests for `hs.uielement` in #870. Hopefully we can eventually overhaul the uielement/application/window interdependencies, and perhaps incorporate your useful-looking axuielement code in a centralized way instead of being spread over several modules.

**Comment by asmagill** [comment]
Note to module writers: we really need to be carful to clear the stack of *all* possible returned values, including error messages, when using `[LuaSkin protectedCallAndTraceback:(int)nargs nresults:(int)nresults]`

**Comment by asmagill** [comment]
This is turning into a collection of minor bug fixes... @cmsj, if you approve the fix I mentioned in #891 for hs.task, I'll add that here as well... I just want a second opinion regarding whether or not it will affect the module's ability to stream output as it arrives or input as it is required.

**Comment by asmagill** [comment]
Assuming Travis likes this (I don't know what drugs CodeCov is on), I would appreciate any feed back... it's a lot of little minor fixes, mainly to keep the stack clean around protectCallAndTraceback, since most of the time these are invoked by callbacks or timers, so the LuaState isn't known at the time and we really should be keeping things as clean as possible since we can't be positive that Lua will clean up after us like it does when invoking a C-function from the Lua interpreter itself.

I'll be checking out hs.webview as I get back to finishing the internal documentation updates, but any additional feedback would be appreciated, especially if anyone uses hs.task with streaming output or input.

I've also addressed #891 and #893.

**Comment by asmagill** [comment]
Assuming Travis likes this and no one objects, I plan on landing this pull this weekend.

**Pull request merged**
