### PR TITLE
hs.notify.warnAboutMissingFunctionTag can be a function

### PR DESCRIPTION
**Pull request by asmagill**
Addresses #1415

### CODE REVIEW

**Comment by latenitefilms** [comment]
Amazing, thank you!

**Comment by asmagill** [comment]
@cmsj, regularly I see failures during the UDP tests... usually it will clear if I tell it to rebuild, though sometimes I have to do so more than once.  Do you know if travis can only handle one of our builds using UDP at a time?  If so, is there any way we can detect other builds and stagger or pause them automatically?

**Comment by cmsj** [comment]
@asmagill I'm not really sure why they fail randomly. I made some changes recently that were supposed to fix it, but they didn't, so I'm thinking at this point probably the easiest option is to SKIP_IN_TRAVIS() that particular test :/

**Comment by asmagill** [comment]
@latenitefilms does this do what you want/need?  If so, I'll go ahead and merge it

**Comment by latenitefilms** [comment]
Looks good to me, thanks again!!

**Pull request merged**
