### PR TITLE
New icons for Big Sur

### PR DESCRIPTION
**Pull request by maebert**
As mentioned in https://github.com/Hammerspoon/hammerspoon/issues/2402#issuecomment-761713629, the tilted icon sticks out next to the glossy new Big Sur candy. This is an attempt at creating an updated icon that lives well next to its macOS 11 brethren:

* Square base with rounded corners
* Plastic gloss and drop shadow for the main element
* Slightly thicker hammer

The 16px and 32px versions are rendered without gloss or shadows to make the lines a little clearer. Feedback welcome of course!

image

### CODE REVIEW

**Comment by dasmurphy** [comment]
@maebert I would like to see the Hammer without the gloss and shadow, then it would be "ok" for me. I really don't like the new icon style for big sur. I really love that everyone can make an icon in his own style and design. Also that may be since i'm on an older system currently. I know the "same" design for all icons is much easier.

With the Hammerspoon icon there is not so much change and the version from you looks ok.

The second i think: Would it be possible to share the source? I think you designed it as an Vector, so it should be easy to export an SVG, AI or Affinity file. I think the source is important, since this is an open source project.

At last i think this is some good progress to the current icon. With some iterations this one would be very nice later...

**Comment by cmsj** [comment]
@maebert thanks for looking at this! I quite like the look. I do wonder if we should make the stem of the hammerspoon shorter - it feels like the Apple icons leave more padding between the edge of the icon and the object inside.

**Comment by cmsj** [comment]
Also it might be worth noting that the source files for our graphical assets live in https://github.com/Hammerspoon/Graphical-Assets and I would ideally prefer to keep some kind of source file in there that I can work with in the future if I need to (at the moment it's Affinity Designer, but SVG would be fine).

**Comment by cmsj** [comment]
For now I've bodged together something myself in #2719 which will be in 0.9.83, but @maebert I'd love to work with you on getting it slightly more aligned with the Big Sur design guidelines. The Affinity Designer file ("Current Source") is in the Graphical Assets repo if that's of any use to you.

**Comment by maebert** [comment]
Hi @cmsj , thanks for the vote of confidence. Super bogged down with work this week but I'll give this an iteration on the weekend!

**Comment by cmsj** [comment]
Gonna close this for now, but please feel free to re-open if you want to revisit this :)

**Pull request closed without merging**
