### PR TITLE
hs.menubar uses hs.image for setIcon

### PR DESCRIPTION
**Pull request by asmagill**

### CODE REVIEW

**Comment by asmagill** [comment]
BTW, re the //Fixme lines... to the asker:  the lua_settop(L, 1) line only make sense if the method is a chain-able one -- it makes sure that, whatever else the method may have done, the return value is the object the method was called on.  Since the methods in question aren't chain-able (their return value indicates success/failure) you can safely remove them.

**Comment by cmsj** [comment]
Thanks, I completely forgot to add that conversion last night. I think that's us completely converted to hs.image! woo :)

**Comment by asmagill** [comment]
I think we still have hs.screen.shotAsJPG and hs.screen.shotAsPNG to convert... divesting the screencapture code from the write to file code and using hs.image.saveToFile would help with #397, I think

**Comment by cmsj** [comment]
@asmagill yup, I'm working on that right now :)

**Pull request merged**
