### PR TITLE
allow hs.application:getMenuItems on a background thread

### PR DESCRIPTION
**Pull request by asmagill**
optional callback allowed for hs.application:getMenuItems allowing its use in a non-blocking manner

### CODE REVIEW

**Comment by cmsj** [comment]
Are we sure this is safe to do on a background thread? If so, +1 from me

**Comment by asmagill** [comment]
I can't find a definitive answer, but its use in this function and in the `hs._asm.axuielement` module hasn't posed a problem for me.  In both cases, the background thread is only used to read (not set) accessibility elements in *other* applications, so basically all it's doing in the background queue is opening an IPC connection to the other app and waiting for a response.

**Comment by cmsj** [comment]
@asmagill ah good point, that makes perfect sense :)

**Comment by asmagill** [comment]
@cmsj absent any objections from you I'm going to merge this tomorrow.

**Pull request merged**
