### PR TITLE
adding HID extension support to toggle and query capslock

### LINKED ISSUE #1362: about CAPS_LOCK key can't work
-- when i run this code,  it work nothing, the capslock light no change
    hs.eventtap.event.newSystemKeyEvent( 'CAPS_LOCK', true):post();
    hs.eventtap.event.newSystemKeyEvent( 'CAPS_LOCK', false):post();

-- when run that code, the capslock light give a flash, a little spark, but hammerspoon console show a error message and then stoped
    -- eventType:FlagsChanged    code:0x39     name:caps_lock   flags:Caps  misc:characters:    
    local  newKey = hs.eventtap.event.newSystemKeyEvent( 0x39, true):post();
    hs.timer.doAfter(0.5, function() hs.eventtap.event.newSystemKeyEvent( 0x39, false):post(); end)

--hammerspoon console show the error message

-- 2017-04-25 04:44:28: *** ERROR: /Users/joys/.hammerspoon/init.lua:92: ERROR: incorrect type 'number' for argument 1 (expected string)
-- stack traceback:
--     [C]: in function 'hs.eventtap.event.newSystemKeyEvent'
--     /Users/joys/.hammerspoon/init.lua:92: in function </Users/joys/.hammerspoon/init.lua:69>
--     /Users/joys/.hammerspoon/init.lua:97: in main chunk
--     [C]: in function 'xpcall'
--     ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
--     (...tail calls...)

this is my mac osX oc define

    -- /System/Library/Frameworks/IOKit.framework/Headers/hidsystem/ev_keymap.h
    
    -- #define NX_NOSPECIALKEY         0xFFFF
    -- #define NX_KEYTYPE_SOUND_UP     0
    -- #define NX_KEYTYPE_SOUND_DOWN       1
    -- #define NX_KEYTYPE_BRIGHTNESS_UP    2
    -- #define NX_KEYTYPE_BRIGHTNESS_DOWN  3
    -- #define NX_KEYTYPE_CAPS_LOCK        4
    -- #define NX_KEYTYPE_HELP         5
    -- #define NX_POWER_KEY            6
    -- #define NX_KEYTYPE_MUTE         7
    -- #define NX_UP_ARROW_KEY         8
    -- #define NX_DOWN_ARROW_KEY       9
    -- #define NX_KEYTYPE_NUM_LOCK     10

### PR DESCRIPTION
**Pull request by dctucker**
Fixes #1362.

Let me know if this needs to be cleaned up in any way; I'm not really used to dealing with other people's xcodeprojects :)

Usage:
```
hs.hid.capslock.toggle()
true
hs.hid.capslock.toggle()
false
print(hs.hid.capslock.get()
false
hs.hid.capslock.set(true)
true
hs.hid.capslock.set(false)
false
```

### CODE REVIEW

**Comment by asmagill** [comment]
Just a question concerning naming... given the `hs.hid.capslock.<fn>` scheme, it *looks* like `capslock` is a submodule of `hid` -- do you anticipate other `hid` submodules at a later time, or is the naming scheme choice more because its the hid subsystem being used to manipulate/query the capslock?

More curiosity than anything else -- functionally it doesn't matter and I personally think that some of the earlier modules were named a little too narrowly in ways that have made grouping related ideas and things together hard or even impossible, so I'm not objecting, just inquiring.

**Comment by asmagill** [comment]
@cmsj, this looks good to me.

**Comment by cmsj** [comment]
Thanks!

**Comment by JaredSartin** [comment]
I know this is closed, but it feels like a good spot to ping.  Would LOVE to see this for numlock. I have a keyboard that has numlocking on it and have done some remapping. I have ended up calling out to https://github.com/damieng/setledsmac - would love to do away with that tool.

**Comment by latenitefilms** [comment]
@JaredSartin - I've added an issue for this here:

https://github.com/Hammerspoon/hammerspoon/issues/1738

**Pull request merged**
