### PR TITLE
base64.encode triggers tostring for non-string input

### PR DESCRIPTION
**Pull request by asmagill**
addresses #1466 

this fix invokes the "__tostring" metamethod on anything that isn't a string or number, so using an image like `hs.base64.encode(hs.image.imageFromName(hs.image.systemImageNames.ActionTemplate))` actually encodes the string "hs.image: NSActionTemplate (0x6000010542a8)" (the address will differ).

Is this sufficient or should it generate an error instead?

### CODE REVIEW

**Comment by cmsj** [comment]
@asmagill I think it might be best to generate an error, otherwise people might think they are getting a base64 encode of the image, and then be surprised when it doesn't decode to an image.

**Comment by asmagill** [comment]
Changes requested have been applied.

**Comment by asmagill** [comment]
Objections?  I think this should be included in the next release for #1433.

**Comment by cmsj** [comment]
No objections

**Pull request merged**
