### PR TITLE
Convert lots of places from lua_Number to lua_Integer

### PR DESCRIPTION
**Pull request by cmsj**

### CODE REVIEW

**Comment by cmsj** [comment]
@asmagill I'd appreciate it if you could give this PR a run around the block, see if you can see anything I've missed, or inappropriately converted. Ideally I'd like to land this fairly soon so we can get a 0.9.32 out the door

**Comment by asmagill** [comment]
built and testing

**Comment by cmsj** [comment]
(rebased on top of current master)

**Comment by cmsj** [comment]
So, I think I've tested all of the functions/methods changed by this PR (famous last words!) and I believe they all work.

Unless I hear any dissent by tomorrow morning, I'll land this and work up a 0.9.32 release :)

**Comment by asmagill** [comment]
I've not noticed any problems either, so I'm good with this.  I'll let you know if that changes.

**Pull request merged**
