### PR TITLE
Added support for Stream Deck Plus

### LINKED ISSUE #3342: Add support for Elgato Stream Deck +
Note to self:

https://github.com/julusian/node-elgato-stream-deck/commit/37479d8a14bffe6eb421164bbaad1161dc302502

https://github.com/bitfocus/companion/commit/b1183862855336992630bbeb5c35f3e34f2b5173

https://github.com/OpenMacroBoard/StreamDeckSharp/issues/50

https://github.com/cgiesche/streamdeck-homeassistant/issues/117

### PR DESCRIPTION
**Pull request by latenitefilms**
- Added `hs.streamdeck:screenCallback(fn)` 
- Added `hs.streamdeck:encoderCallback(fn)`
- Added `hs.streamdeck:setScreenImage(encoder, image)`
- Closes #3342

**TEST CODE:**
```lua
local logger = require("hs.logger")
logger.defaultLogLevel = 'debug'
local log = logger.new("streamDeck")
local streamdeck = require("hs.streamdeck")

obj = nil

local function discoveryCallback(connected, object)
    log.df("Stream Deck Callback. Connected: %s, Object: %s", connected, object)

    if connected and object then    
        --------------------------------------------------------------------------------
        -- Button Callback:
        --------------------------------------------------------------------------------
        object:buttonCallback(function(object, buttonID, pressed)
            log.df("[BUTTON] object: %s, buttonID: %s, pressed: %s", object, buttonID, pressed)
        end)
        
        --------------------------------------------------------------------------------
        -- Encoder Callback:
        --------------------------------------------------------------------------------
        object:encoderCallback(function(object, buttonID, pressed, turningLeft, turningRight)
            if turningLeft then
                log.df("[ENCODER] object: %s, buttonID: %s, turned: LEFT", object, buttonID)
            elseif turningRight then
                log.df("[ENCODER] object: %s, buttonID: %s, turned: RIGHT", object, buttonID)
            else
                log.df("[ENCODER] object: %s, buttonID: %s, pressed: %s", object, buttonID, pressed)
            end
        end)
        
        --------------------------------------------------------------------------------
        -- Screen Callback:
        --------------------------------------------------------------------------------
        object:screenCallback(function(object, eventType, startX, startY, endX, endY)        
            log.df("[SCREEN] object: %s, eventType: %s, startX: %s, startY: %s, endX: %s, endY: %s", object, eventType, startX, startY, endX, endY)        
        end)
        
        --------------------------------------------------------------------------------
        -- Set Image Buttons:
        --------------------------------------------------------------------------------
        for i=1, 8 do
            object:setButtonImage(i, hs.image.imageFromAppBundle("com.apple.finder"))
        end
    
        --------------------------------------------------------------------------------
        -- Set LCD Images:
        --------------------------------------------------------------------------------
        for i=1, 4 do
            object:setScreenImage(i, hs.image.imageFromAppBundle("com.apple.finder"))
        end
    
        --------------------------------------------------------------------------------
        -- Save to global `obj` object for testing:
        --------------------------------------------------------------------------------
        obj = object
    end    

end

streamdeck.init(discoveryCallback)
```

### CODE REVIEW

**Comment by latenitefilms** [comment]
Note to self - test code:

```lua
local logger = require("hs.logger")
logger.defaultLogLevel = 'debug'
local log = logger.new("streamDeck")
local streamdeck = require("hs.streamdeck")

obj = nil

local function discoveryCallback(connected, object)
	log.df("Stream Deck Callback. Connected: %s, Object: %s", connected, object)

	if connected and object then
		object:buttonCallback(function(object, buttonID, pressed)
			log.df("object: %s, buttonID: %s, pressed: %s", object, buttonID, pressed)
		end)
	end
	
	for i=1, 8 do
    	--object:setButtonColor(i, hs.drawing.color.red)    	
    	object:setButtonImage(i, hs.image.imageFromAppBundle("com.apple.finder"))
    end
	
	obj = object

end

streamdeck.init(discoveryCallback)
```

**Comment by latenitefilms** [comment]
@cmsj - This now all seems to be working if you want to review?

**Comment by cmsj** [comment]
@latenitefilms looking good! One thought - could the three new Lua methods mention that they're specific to the Deck Plus?

**Comment by latenitefilms** [comment]
Documentation updated. Let me know if you want any other tweaks or changes. Thanks!

**Pull request merged**
