### PR TITLE
Fix detached menus so they don't leave traces in menubar

### PR DESCRIPTION
**Pull request by asmagill**
address #1567 and menubar notes in #2098
also clears compiler warnings during build

### CODE REVIEW

**Comment by asmagill** [comment]
Details, for the interested:

Cleaned up compiler warnings, mostly converting nested objective-c calls into multiple lines which verify object existence before invoking next method.

Converted assignments of `nil` assigned to `void *` pointers to `NULL` since `nil` is suppose to be reserved for objective-c objects and `NULL` is used used for C type pointers; the compiler is supposed to be smart enough to correct for this, but this is more explicit.

Fix for persisting pop-up menus: when originally written, because the `NSStatusItem` class does not list an initializer, all status items were created through the `NSStatusBar` class (which are attached to the menubar) and pop-up menus were removed from the menubar with the `removeStatusItem:` method.

This worked until sometime around macOS 10.11 or so (not sure exactly); after that, because the status item originated in the menu bar, macOS would occasionally re-attach the status item, even after a removal, if the `NSStatusItem` object wasn't collected via ARC quickly enough (we kept it around in our own wrapper because the `NSMenu` used as the pop-up was a property of the `NSStatusItem` object.)

This change uses the generic initializer that all descendants of `NSObject` inherit (e.g. `[[NSStatusItem alloc] init]`) and then copies the properties of the status item in the menubar into this new status item, and then allows the status item which was created in the menubar to be collected immediately, preventing traces of it from being re-added to the menubar.

**Comment by asmagill** [comment]
@cmsj, can't see BCH details for this either:
Screen Shot 2019-08-01 at 3 42 42 PM

**Comment by cmsj** [comment]
I can’t even see BCH these days 😕 I’ll remove it at some point.

**Comment by latenitefilms** [comment]
As discussed in the other issue, I've tested this code with CommandPost, and all working great - so feel free to merge away when ready @cmsj !

**Pull request merged**
